fix visibility of button when unauthorized
kioku-project/kioku pull request #107
Opened 2023-10-05 12:05 UTC by leonie2003

Ich hab das mit dem Edit der Card auch gleich geändert, hab die visibility des edit buttons auf hidden gesetzt

2023-10-06 07:51 UTC, Julian702 requested changes
Some changes before we can merge this pr:

1. Please run Prettier for formatting and import sorting
2. Please rewrite pr description in english
3. Could you create an issue for the changes in the Flashcard component?
4. Have a look at the code smell found by SonarCloud

2023-10-06 07:51 UTC, Julian702 commented on frontend/components/flashcard/CardList.tsx
> +			{isAuthorized()?(<Card card={{ cardID: "", sides: [], deckID: deck.deckID }}/>):(<></>)}
```suggestion
			{ deck.groupRole && GroupRole[deck.groupRole] >= GroupRole.WRITE && <Card card={{ cardID: "", sides: [], deckID: deck.deckID }}/>)}
```
remove function below and insert statement here

2023-10-06 07:51 UTC, Julian702 commented on frontend/components/flashcard/CardList.tsx
> +	}
```suggestion

	function isAuthorized(){
		return deck.groupRole && GroupRole[deck.groupRole] >= GroupRole.WRITE
	}
```
if statement not necessary
```suggestion
```
remove function as stated above

2023-10-06 07:51 UTC, Julian702 commented on frontend/components/flashcard/Flashcard.tsx
> +import { GroupRole } from "@/types/GroupRole";
please run prettier to format changes and sort imports

2023-10-06 07:51 UTC, Julian702 commented on frontend/components/flashcard/Flashcard.tsx
> +	 */
copy paste error

2023-10-06 07:51 UTC, Julian702 commented on frontend/components/flashcard/Flashcard.tsx
> +	role,
```suggestion
	editable,
```
s.a.

2023-10-06 07:51 UTC, Julian702 commented on frontend/components/flashcard/Flashcard.tsx
> +									visibility={isAuthorized() ? "visible" : "hidden"}
lets grey out this button instead of hiding it for better user experience

2023-10-06 07:51 UTC, Julian702 commented on frontend/components/navigation/Tabs/CardsTab.tsx
> +import { Deck } from "@/types/Deck";
```suggestion
import { Deck as DeckType} from "@/types/Deck";
```
just for clarification

2023-10-06 07:51 UTC, Julian702 commented on frontend/components/navigation/Tabs/CardsTab.tsx
> +	deck: Deck;
```suggestion
	deck: DeckType;
```

2023-10-06 07:51 UTC, Julian702 commented on frontend/components/navigation/Tabs/CardsTab.tsx
> +								role={deck.groupRole}
s.a.

2023-10-06 07:51 UTC, Julian702 commented on frontend/next.config.js
> +				destination: "http://localhost:80/api/:path*",
```suggestion
				destination: "http://frontend_proxy:80/api/:path*",
```
please revert this change sice it is for local development only

2023-10-06 07:51 UTC, Julian702 commented on frontend/pages/deck/[id]/index.tsx
> +											deck={{ ...deck, deckID: deck.deckID, groupRole: group.groupRole }}
```suggestion
											deck={{ ...deck, groupRole: group.groupRole }}
```
deckID is part of deck

2023-10-06 07:51 UTC, Julian702 commented on package-lock.json
> +}
```suggestion
```

2023-10-06 07:51 UTC, Julian702 commented on frontend/components/flashcard/Flashcard.tsx
> +	}
```suggestion
```
s.a.

2023-10-06 07:51 UTC, Julian702 commented on frontend/components/flashcard/Flashcard.tsx
> +	role?: keyof typeof GroupRole
```suggestion
	editable?: boolean
```
maybe change like this as the role isn't really needed here

2023-10-06 08:20 UTC, darmiel commented on .gitignore
> +frontend/next.config.js
**tip**: you can add ignored files to `.git/info/exclude`  to only ignore them locally :)

2023-10-06 11:08 UTC, leonie2003 commented on frontend/components/flashcard/Flashcard.tsx
> +									visibility={isAuthorized() ? "visible" : "hidden"}
Can I find the respective design on storybook?

2023-10-06 13:27 UTC, darmiel commented
FYI @leonie2003 you can restore the `.gitignore` (or any file to the state before this PR) using:
```
git checkout 23e94c6c7bf2aa6d96e4052ea9d7e3f0d8da76d1 -- .gitignore docker-compose.yml frontend/next.config.js
```
In your last commit you deleted the `.gitignore` file not only from the pull request but from the project

2023-10-06 13:38 UTC, leonie2003 commented
Oh, okay
I'll do that
thanks

2023-10-07 18:54 UTC, TomRomeo requested changes
Please fix SonarCloud code smells

2023-10-09 09:11 UTC, Julian702 requested changes
Just found two minor nits, well done 👍

2023-10-09 09:11 UTC, Julian702 commented on frontend/components/flashcard/Flashcard.tsx
> +	 * permissions to edit
```suggestion
	 * Permissions to edit
```
inofficial project standard

2023-10-09 12:04 UTC, Julian702 approved these changes

2023-10-09 12:23 UTC, TomRomeo approved these changes
Looks great, please don't forget to squash when merging :)

2023-10-09 13:29 UTC, darmiel approved these changes

2023-10-10 07:35 UTC, memeToasty approved these changes

2023-10-10 12:43 UTC, merged