Fix storybook and chromatic errors
kioku-project/kioku pull request #124
Opened 2023-10-11 10:42 UTC by Julian702

## Description

This pr updates some components and stories to resolve storybook / chromatic issues. Therefore the Deck and CardList component are wrapped into new components that handle fetching the data.

2023-10-11 10:58 UTC, darmiel requested changes

2023-10-11 10:58 UTC, darmiel commented on frontend/components/deck/Deck.tsx
> +				{!!deck?.dueCards && deck.dueCards > 0 && (
```suggestion
				{deck?.dueCards > 0 && (
```

2023-10-11 10:58 UTC, darmiel commented on frontend/components/flashcard/CardList.tsx
> +	return <CardList deck={deck} cards={cards?.cards} {...props}></CardList>;
```suggestion
	return <CardList deck={deck} cards={cards?.cards} {...props} />;
```

2023-10-11 10:58 UTC, darmiel commented on frontend/components/navigation/Tabs/CardsTab.tsx
> +			></FetchCardList>
```suggestion
			/>
```

2023-10-11 11:06 UTC, TomRomeo requested changes
I am not really happy with the naming. I would rather have the component with the logic have the simple name (eg. `Deck`) and the purely visual component to have another name (eg. `DeckVisual`) since developers will mostly use the components with logic in other parts of the program.

2023-10-11 11:15 UTC, darmiel approved these changes

2023-10-11 11:55 UTC, memeToasty approved these changes

2023-10-11 17:44 UTC, 4KevR approved these changes

2023-10-20 08:35 UTC, TomRomeo approved these changes
Really unhappy with the naming but since the majority seems to like it... 😭

2023-10-20 09:06 UTC, merged