Refactor login page
kioku-project/kioku pull request #126
Opened 2023-10-16 17:45 UTC by Julian702

## Description

This pr refactors the login page including the InputField component to make it more user friendly and responsive.

## Problems

I'm aware of the following problems that have to be solved before merging this pr:
- [ ] go to next InputField on the login page with `tab`
- [ ] settings tab is crashing
- [ ] passwords have to match when registering a new account

2023-10-16 17:56 UTC, darmiel commented on frontend/components/form/InputField.tsx
> +			onChange = () => {},
consider changing this to an `onValueChange (newVal: string) => void` callback, because we probably don't need the event anytime soon and we can just pass state-setters more easily:

```tsx
const [text, setText] = useState("")
<InputField value={text} onValueChange={setText} ... />
```

2023-10-16 17:56 UTC, darmiel commented on frontend/components/form/InputField.tsx
> +						anchorSelect={`#tooltip-${id}`}
instead of `anchorSelect`, rather use `<Tooltip id={id} />` and `data-tooltip-id` on the icons

2023-10-18 14:41 UTC, Julian702 commented on frontend/components/form/InputField.tsx
> +			onChange = () => {},
I think it could be useful to be able to access the event here. I also see no reason to limit this unnecessarily.

2023-10-20 08:56 UTC, darmiel commented on frontend/components/form/InputField.tsx
> +	statusIcon?: "none" | "success" | "error" | "warning" | "info";
```suggestion
	statusIcon?:  keyof typeof statusIcons;
```

2023-10-20 08:56 UTC, darmiel commented on frontend/components/form/InputField.tsx
> +}
```suggestion
const statusIcons = {
	none: <></>,
	success: <Check className="text-kiokuDarkBlue outline-none" />,
	error: <AlertCircle className="text-kiokuRed outline-none" />,
	warning: <AlertTriangle className="text-kiokuYellow outline-none" />,
	info: <Info className="text-kiokuDarkBlue outline-none" />,
}

function getIcon(status: keyof typeof statusIcons, id: string): ReactNode {
	return <span data-tooltip-id={`tooltip-${id}`}>{statusIcons[status]}</span>;
}
```

2023-10-20 08:56 UTC, darmiel commented on frontend/components/form/InputField.tsx
> +							size ?? getSize[size]
```suggestion
							size && getSize[size]
```

2023-10-20 08:56 UTC, darmiel commented on frontend/pages/login.tsx
> +									setLogin(!login);
```suggestion
									setLogin((prev) => !prev);
```

2023-10-20 08:56 UTC, darmiel commented on frontend/pages/login.tsx
> +		let url = "/api/register";
```suggestion
		const url = "/api/register";
```

or just inline since you don't use `url` any time soon

2023-10-21 12:59 UTC, TomRomeo requested changes
looks very good already! Just some minor nits.

2023-10-24 07:52 UTC, Julian702 commented on frontend/components/Text.tsx
> +	responsive?: boolean;
It's used in the SettingsTab

2023-10-24 08:14 UTC, TomRomeo approved these changes

2023-10-24 08:15 UTC, TomRomeo commented
Please fix the SonarCloud code smell before merging

2023-10-24 08:22 UTC, 4KevR approved these changes

2023-10-24 08:54 UTC, merged