Rewrite of group and deck types
kioku-project/kioku pull request #128
Opened 2023-10-18 11:48 UTC by TomRomeo

# Description
This PR rewrites the types for groups and adds types for decks.

## GroupTypes:
```
OPEN
REQUEST
CLOSED
```
## DeckTypes:
```
PUBLIC
PRIVATE
```

A user can request access on open groups and will instantly be added as a `READ` user.
A user can request access on groups of the type `REQUEST` and will have to be added by admins.
A user can not request access on groups of the type `Closed`.

A member of a group can see public and private decks.
External users can only see public decks.

## Resolved Issues
resolves #115
resolves #116

2023-10-18 12:58 UTC, 4KevR requested changes
Looks great, just some nits for discussion.

2023-10-18 12:58 UTC, 4KevR commented on backend/services/carddeck/handler/carddeck.go
> +		}
I would suggest doing this filtering in the db layer

2023-10-18 12:58 UTC, 4KevR commented on backend/services/frontend/handler/frontend.go
> +	return c.JSON(converter.ProtoDeckToFiberDeckConverter(deck))
I think a new serializer would be better than doing it twice here.

2023-10-18 14:36 UTC, TomRomeo commented on backend/pkg/converter/typeConverter_test.go
>  	}
implemented in 6992733

2023-10-18 14:36 UTC, TomRomeo commented on backend/services/carddeck/handler/carddeck.go
> +		}
That is smart, I didn't think of that!
implemented in 6992733

2023-10-18 14:36 UTC, TomRomeo commented on backend/services/carddeck/handler/carddeck.go
> +		logger.Info(req.DeckType.String())
removed in 6992733

2023-10-18 14:37 UTC, TomRomeo commented on backend/services/frontend/handler/frontend.go
> +	return c.JSON(converter.ProtoDeckToFiberDeckConverter(deck))
implemented in 6992733

2023-10-18 16:37 UTC, 4KevR approved these changes

2023-10-18 21:07 UTC, TomRomeo commented on backend/pkg/model/deck.go
> +
I already discussed the naming with @Julian702 and @memeToasty and we came to the conclusion to name the types in this manner since both also do quite different things and in order to keep previous naming schemes.

2023-10-18 21:07 UTC, TomRomeo commented on backend/pkg/model/group.go
> +	Closed  GroupType = "closed"
same reasoning as above. Do you dislike the current naming?

2023-10-18 21:09 UTC, TomRomeo commented on backend/services/collaboration/proto/collaboration.proto
> +	INVALID = 3;
Negative values seem to be possible but discouraged by the [proto documentation](https://protobuf.dev/programming-guides/proto2/#:~:text=Enumerator%20constants%20must%20be%20in,definition%20in%20your%20.proto%20file.)

2023-10-18 22:12 UTC, darmiel commented on backend/services/collaboration/proto/collaboration.proto
> +	INVALID = 3;
I see, maybe then start with the invalid one at 0?

2023-10-18 22:15 UTC, darmiel commented on backend/pkg/model/group.go
> +	Closed  GroupType = "closed"
I don't know, when reading this for the first time I didn't really think of the group visibility and I had to get some additional context.

Also consider adding a suffix to the constants, because "model.Closed" was a bit weird until I got the context I needed. Maybe change this to "ClosedGroupType" since the package, "model" gives no hint and the usage of this constant

2023-10-19 04:34 UTC, TomRomeo commented on backend/services/collaboration/proto/collaboration.proto
> +	INVALID = 3;
Since the zero value also defines the default value in Proto, I am not sure if putting `INVALID` at the top is a good idea.

2023-10-20 06:32 UTC, Julian702 commented on backend/pkg/model/deck.go
> +
Can't remember. I think we should go with groupType and visibility for decks since as you mentioned both "do quite different things" and we should represent this in different naming.

2023-10-20 06:33 UTC, TomRomeo commented on backend/pkg/model/deck.go
> +
Alright, feel free to rename them ☺️

2023-10-20 06:37 UTC, TomRomeo commented on backend/pkg/model/group.go
> +	Closed  GroupType = "closed"
That is because it is not about group visibility but about the join behavior for new members. That's why visibility is the wrong naming here.

2023-10-20 06:37 UTC, TomRomeo commented on backend/pkg/converter/typeConverter.go
> +	}
fixed 61af69a

2023-10-20 06:38 UTC, TomRomeo commented on backend/pkg/converter/typeConverter.go
> +		return pbCardDeck.DeckType_PRIVATE
fixed in 61af69a

2023-10-20 06:52 UTC, TomRomeo commented on backend/pkg/model/group.go
> +	Closed  GroupType = "closed"
I renamed the group- and decktypes in dab3e5f for more clarity when using them in the backend.

2023-10-20 07:02 UTC, darmiel approved these changes

2023-10-20 08:32 UTC, 4KevR commented on backend/pkg/model/deck.go
> +
I also think that DeckType is more concise as Visibility as the naming does not imply to give a property about decks. The consistency for DeckType and GroupType is also good.

2023-10-24 14:03 UTC, Julian702 commented
Please set "PRIVATE" as default `deckType`

2023-10-28 09:18 UTC, memeToasty approved these changes

2023-11-06 11:17 UTC, Julian702 approved these changes

2023-11-06 11:19 UTC, merged