implemented index page
kioku-project/kioku pull request #13
Opened 2023-04-12 13:01 UTC by TomRomeo

Title says it all

2023-04-13 07:15 UTC, Julian702 requested changes

2023-04-13 07:15 UTC, Julian702 commented on frontend/components/deck/DeckOverviewTile.stories.ts
> +export const Default: Story = {
would suggest to change names (default without cards)

2023-04-13 07:15 UTC, Julian702 commented on frontend/components/group/GroupAsideTile.stories.tsx
> +export const Default: Story = {
same here

2023-04-13 07:15 UTC, Julian702 commented on frontend/components/group/GroupAsideTile.tsx
> + * UI component for A group in the side bar
```suggestion
 * UI component for a group in the side bar
```

2023-04-13 07:15 UTC, Julian702 commented on frontend/components/group/GroupOverviewTile.stories.tsx
> +			{ name: "Deck1", count: 1 },
maybe start from zero?

2023-04-13 07:15 UTC, Julian702 commented on frontend/components/group/GroupOverviewTile.tsx
> +	 * Decks to be displayed in a Group
```suggestion
	 * Decks to be displayed in a group
```

2023-04-13 07:16 UTC, TomRomeo commented on frontend/components/group/GroupOverviewTile.stories.tsx
> +			{ name: "Deck1", count: 1 },
nah

2023-04-13 07:17 UTC, memeToasty approved these changes

2023-04-16 10:51 UTC, 4KevR requested changes
Looks very good, see comments for proposed adjustments.

2023-04-16 10:51 UTC, 4KevR commented on frontend/components/navigation/Navigation.tsx
> +import Image from "next/image";
It would be great to remove unused imports from this file.

2023-04-16 10:51 UTC, 4KevR commented on frontend/components/navigation/Navigation.tsx
> +					<aside className="bg-[#CCCCCC] h-full p-4 w-5/6 md:w-1/6 absolute md:relative z-10">
Maybe this would lead to a more general question about structuring the project but I would suggest to use custom css files for the modules and to define classes for the components. In my opinion, it would make the code more readable and we could have reusable css definitions in the styles directory in the form of css modules (*.module.css). What do you think about this?

2023-04-16 12:52 UTC, TomRomeo commented on frontend/components/navigation/Navigation.tsx
> +					<aside className="bg-[#CCCCCC] h-full p-4 w-5/6 md:w-1/6 absolute md:relative z-10">
I do understand your point, but I think we should not discuss this within this pr since most of the frontend code so far has used TailwindCSS inline styling. If we want to change that, we should create a refactoring task and rework all the frontend code at once.

2023-04-16 13:36 UTC, 4KevR commented on frontend/components/navigation/Navigation.tsx
> +					<aside className="bg-[#CCCCCC] h-full p-4 w-5/6 md:w-1/6 absolute md:relative z-10">
Good idea👍

2023-04-16 15:25 UTC, 4KevR approved these changes

2023-04-17 07:02 UTC, Julian702 approved these changes
🫤

2023-04-17 07:11 UTC, merged