added Modify User backend logic
kioku-project/kioku pull request #133
Opened 2023-10-21 13:26 UTC by TomRomeo

## Description
This PR implements the backend logic to modify user data.

## Endpoint
`PUT` `/api/user`
```json
{
  "userName": "",
  "userEmail": "",
  "userPassword":""
}
```
## Resolved Issues
#113

2023-10-22 09:49 UTC, memeToasty approved these changes

2023-10-22 12:38 UTC, darmiel commented on backend/services/frontend/handler/frontend.go
> +	})
use a struct

```go
type modifyUserPayload struct {
  UserEmail string `json:"userEmail"`
  UserName string `json:"userName"`
  UserPassword string `json:"userPassword"`
}
// ...
var data modifyUserPayload
err := c.BodyParser(&data)
// ...
```
```diff
- UserEmail: data["userEmail"],
+ UserEmail: data.UserEmail,
```

2023-10-22 12:38 UTC, darmiel commented on backend/services/user/handler/user.go
> +	rsp.Success = true
You should probably handle this error (and not return `rsp.Success = true` if there is an error)

2023-10-23 09:02 UTC, 4KevR approved these changes
No other comments

2023-10-30 14:05 UTC, TomRomeo commented on backend/services/frontend/handler/frontend.go
> +	})
implemented in 8344962

2023-10-30 14:05 UTC, TomRomeo commented on backend/services/user/handler/user.go
> +	rsp.Success = true
implemented in 8344962

2023-11-03 17:13 UTC, darmiel approved these changes

2023-11-04 16:08 UTC, Julian702 requested changes
Works fine, just some nits and inconsistent error messages compared to /api/register

2023-11-04 16:08 UTC, Julian702 commented on backend/api-documentation/user/modify user.bru
> +  seq: 7
Has to be 6 and /user/delete user.bru has to be updated to 7
```suggestion
  seq: 6
```

2023-11-04 16:08 UTC, Julian702 commented on backend/api-documentation/user/modify user.bru
> +    "userPassword":""
Lets fill this with example values and swap email with name to match project default
```suggestion
    "userEmail": "test@test.test",
    "userName": "test",
    "userPassword":"test"
```

2023-11-04 16:27 UTC, TomRomeo commented on backend/api-documentation/user/modify user.bru
> +  seq: 7
changed in 74eee5b

2023-11-04 16:27 UTC, TomRomeo commented on backend/api-documentation/user/modify user.bru
> +    "userPassword":""
changed in 74eee5b

2023-11-04 18:11 UTC, Julian702 commented on backend/api-documentation/user/modify user.bru
> +  seq: 7
You have not updated the documentation for the delete user endpoint. Although I even mentioned this^^

2023-11-04 18:14 UTC, Julian702 reviewed
You have implemented two code smells with your latest commit.

2023-11-06 07:50 UTC, Julian702 requested changes
One last nit and it's also possible to change the password to "". After that I'm no longer able to login to my account.

2023-11-06 07:50 UTC, Julian702 commented on backend/api-documentation/user/modify user.bru
> +    "userPassword":"test"
```suggestion
    "userPassword": "test"
```

2023-11-06 08:08 UTC, Julian702 approved these changes
Hast du dir verdient <3

2023-11-06 08:10 UTC, merged