Fix flashcard multiline description
kioku-project/kioku pull request #139
Opened 2023-10-22 11:45 UTC by JJthere

## Description

This PR fixes flashcard multiline descriptions, by changing the InputField to a TextArea.

2023-10-22 12:30 UTC, Julian702 requested changes
Good job, found just one small nit. 👍

2023-10-22 12:30 UTC, Julian702 commented on frontend/components/form/TextArea.tsx
> +				className={` h-full w-full resize-none rounded-md border-eggshell bg-eggshell font-medium text-kiokuLightBlue outline-none`}
Is there a reason to use a border in the same color as the background which is not even visible?
Maybe also think about making the background transparent to use the component more universally.
```suggestion
				className={` h-full w-full resize-none rounded-md bg-transparent font-medium text-kiokuLightBlue outline-none`}
```

2023-10-22 12:41 UTC, darmiel reviewed
Good job, found just three small nits. 👍

2023-10-22 12:41 UTC, darmiel commented on frontend/components/form/TextArea.tsx
> +				className={` h-full w-full resize-none rounded-md bg-transparent font-medium text-kiokuLightBlue outline-none`}
```suggestion
				className="h-full w-full resize-none rounded-md bg-transparent font-medium text-kiokuLightBlue outline-none"
```

2023-10-22 12:41 UTC, darmiel commented on frontend/components/form/TextArea.tsx
> +	 * optional change handler
```suggestion
	 * Change handler
```

2023-10-22 12:41 UTC, darmiel commented on frontend/components/form/TextArea.tsx
> +	 * unique identifier
```suggestion
	 * Unique identifier
```

2023-10-22 15:45 UTC, memeToasty approved these changes

2023-10-22 18:56 UTC, darmiel commented on frontend/components/form/TextArea.tsx
> +}
any reason to use these predefined props and not just allow all HTML Text Area props?

2023-10-22 18:56 UTC, darmiel approved these changes

2023-10-23 07:11 UTC, TomRomeo approved these changes
💖

2023-10-23 11:02 UTC, JJthere commented on frontend/components/form/TextArea.tsx
> +}
No,
we will need to address this problem in another pr, because of its reoccurrence in other files.

2023-10-23 11:36 UTC, 4KevR approved these changes

2023-10-23 12:06 UTC, merged