refactored navbar
kioku-project/kioku pull request #150
Opened 2023-10-24 12:19 UTC by TomRomeo

## Description
This PR refactors the navbar to the `_app.tsx` layout file so it doesn't get re-rendered on every page navigation.

## Resolved Issues
resolves #141

2023-10-24 12:29 UTC, memeToasty approved these changes

2023-10-24 13:37 UTC, darmiel commented on frontend/components/navigation/Navbar.tsx
>  		<div
use `nav` instead of `div`

2023-10-24 13:37 UTC, darmiel commented on frontend/components/navigation/Navbar.tsx
> +					<div className="flex flex-row">
why flex (-row) this?

2023-10-24 13:37 UTC, darmiel commented on frontend/pages/features.tsx
> +		<div className="flex flex-1">
use `main` instead of `div`

2023-10-24 13:37 UTC, darmiel approved these changes

2023-11-03 16:13 UTC, TomRomeo commented on frontend/components/navigation/Navbar.tsx
>  		<div
chaged in 6ed433b

2023-11-03 16:13 UTC, TomRomeo commented on frontend/components/navigation/Navbar.tsx
> +					<div className="flex flex-row">
removed in 6ed433b

2023-11-03 16:14 UTC, TomRomeo commented on frontend/pages/features.tsx
> +		<div className="flex flex-1">
changed in 6ed433b

2023-11-04 12:04 UTC, Julian702 requested changes
There are some small problems we have to fix:
- [x] The login button is not updated after login.
- [x] The Navbar is now displayed on the login page. That's why the logo is displayed twice and the login button in the Navbar is also not convenient on the login page. I would suggest removing the login button on the login page from the navbar and removing the logo from the login page. Moreover, the login page is not centered.

Furthermore, I don't really like the layout changes on the home page and we should try to restore the old layout after the refactoring.

2023-11-04 15:11 UTC, TomRomeo commented on frontend/components/navigation/Navbar.tsx
> +	}, []);
refactored in d9cf355

2023-11-04 15:11 UTC, TomRomeo commented on frontend/components/navigation/Navbar.tsx
> +					<Logo onClick={() => router.push("/")}></Logo>
moved in d9cf355

2023-11-04 15:11 UTC, TomRomeo commented on frontend/components/navigation/Navbar.tsx
> +					<div className="flex">
removed in d9cf355

2023-11-04 15:11 UTC, TomRomeo commented on frontend/components/navigation/Navbar.tsx
> +					<Logo onClick={() => router.push("/home")}></Logo>
moved in d9cf355

2023-11-04 18:07 UTC, Julian702 requested changes
The getting startedg buttons are still not working as expected. Please review and test your changes afterwards. 
It is also possible to access the login page when logged in. In this case, the Logout button is displayed in the NavBar. We should change this behavior. I would suggest either to be redirected directly when you go to the login page logged in or to be logged out automatically.

2023-11-04 18:07 UTC, Julian702 commented on frontend/pages/features.tsx
> +						onClick={() => hasCookie("access-token") ? router.push("/") : router.push("/login")}
This does not work. The method `hasCookie` returns `false`. Even if I am logged in, I am redirected to the login by clicking on the link or the button on the home page.

2023-11-04 18:07 UTC, Julian702 commented on frontend/pages/home.tsx
> +								onClick={() => hasCookie("access-token") ? router.push("/") : router.push("/login")}
s.a.

2023-11-05 10:59 UTC, TomRomeo commented on frontend/pages/features.tsx
> +						onClick={() => hasCookie("access-token") ? router.push("/") : router.push("/login")}
This was due to the wrongly quoted cookie name. The actual name is `access_token`.
I fixed it in b4d3352

2023-11-05 11:00 UTC, TomRomeo commented on frontend/pages/home.tsx
> +								onClick={() => hasCookie("access-token") ? router.push("/") : router.push("/login")}
also fixed in b4d3352

2023-11-05 11:01 UTC, TomRomeo commented
> [...] It is also possible to access the login page when logged in. In this case, the Logout button is displayed in the NavBar. We should change this behavior. I would suggest either to be redirected directly when you go to the login page logged in or to be logged out automatically.
I changed the behavior to redirect the user away from the login page when they are logged in.

2023-11-05 11:10 UTC, Julian702 approved these changes

2023-11-05 14:26 UTC, 4KevR requested changes
Looks great, just some small nits.

2023-11-05 14:26 UTC, 4KevR commented on frontend/components/navigation/Navbar.tsx
>  import { Inter } from "next/font/google";
Inter is not used anymore in this file. Remove import and usage.

2023-11-05 14:26 UTC, 4KevR commented on frontend/components/navigation/Navbar.tsx
> +import router, { useRouter } from "next/router";
Unused import `router`

2023-11-05 14:26 UTC, 4KevR commented on frontend/components/navigation/Navbar.tsx
>  					className="invisible h-full justify-end sm:visible"
```suggestion
					className="invisible justify-end sm:visible h-7 md:h-10"
```
The Login Button is causing a shift in the position of the Logo when changing from `home` to `login` page.

2023-11-05 14:56 UTC, TomRomeo commented on frontend/components/navigation/Navbar.tsx
>  import { Inter } from "next/font/google";
removed in 8c37524

2023-11-05 14:56 UTC, TomRomeo commented on frontend/components/navigation/Navbar.tsx
> +import router, { useRouter } from "next/router";
removed in 8c37524

2023-11-05 14:56 UTC, TomRomeo commented on frontend/components/navigation/Navbar.tsx
>  					className="invisible h-full justify-end sm:visible"
changed in 8c37524

2023-11-05 16:14 UTC, 4KevR approved these changes

2023-11-06 09:32 UTC, merged