Add copy deck route
kioku-project/kioku pull request #163
Opened 2023-11-06 12:17 UTC by TomRomeo

## Description
This PR implements the backend logic to copy decks

## Resolved Issues
resolves #117

2023-11-06 12:49 UTC, 4KevR requested changes
Looks great, just some small nits.

2023-11-06 12:49 UTC, 4KevR commented on backend/services/carddeck/handler/carddeck.go
> +		err, deckType = converter.MigrateProtoDeckTypeToModelDeckType(*req.DeckType)
Please refactor method to first return the `deckType` and then the `err` to make it consistent with the existing codebase.

2023-11-06 12:49 UTC, 4KevR commented on backend/services/carddeck/handler/carddeck.go
> +	return nil
`rsp` of type `DeckResponse` is not used. Suggestion: Use the `IDResponse` or `SuccessResponse`, depending on the needs of the frontend.

2023-11-06 13:18 UTC, darmiel reviewed
awsom

2023-11-06 13:18 UTC, darmiel commented on backend/services/carddeck/handler/carddeck.go
> +		err, deckType = converter.MigrateProtoDeckTypeToModelDeckType(*req.DeckType)
swap this if-statement

```suggestion
	if req.DeckType != nil {
		deckType, err = converter.MigrateProtoDeckTypeToModelDeckType(*req.DeckType)
	} else {
		deckType = model.PrivateDeckType
```

2023-11-06 13:18 UTC, darmiel commented on backend/services/frontend/handler/frontend.go
> +	var data map[string]string
create a struct for this

2023-11-06 13:18 UTC, darmiel commented on backend/services/frontend/handler/frontend.go
> +	if deckName := data["deckName"]; deckName == "" {
there is no need to create this scoped `deckName` variable. just do

```go
if data["deckName"] == "" {
```

(after the struct change):

```go
if payload.DeckName == "" {
```

2023-11-06 14:02 UTC, TomRomeo commented on backend/services/carddeck/handler/carddeck.go
> +		err, deckType = converter.MigrateProtoDeckTypeToModelDeckType(*req.DeckType)
done in 2b00ace

2023-11-06 14:02 UTC, TomRomeo commented on backend/services/carddeck/handler/carddeck.go
> +	e.store.CreateDeck(newDeck)
handled in 2b00ace

2023-11-06 14:02 UTC, TomRomeo commented on backend/services/carddeck/handler/carddeck.go
> +	return nil
changed to `IDResponse` in 2b00ace

2023-11-06 14:02 UTC, TomRomeo commented on backend/services/frontend/handler/frontend.go
> +	return c.SendStatus(200)
done in 2b00ace

2023-11-06 14:03 UTC, TomRomeo commented on backend/services/carddeck/handler/carddeck.go
> +		err, deckType = converter.MigrateProtoDeckTypeToModelDeckType(*req.DeckType)
implemented in 2b00ace

2023-11-06 14:03 UTC, TomRomeo commented on backend/services/frontend/handler/frontend.go
> +	if deckName := data["deckName"]; deckName == "" {
done in 2b00ace

2023-11-06 14:41 UTC, 4KevR approved these changes

2023-11-06 14:59 UTC, darmiel approved these changes

2023-11-06 14:59 UTC, TomRomeo commented on backend/services/carddeck/handler/carddeck.go
> +	}
✅

2023-11-08 08:03 UTC, memeToasty approved these changes

2023-11-28 08:16 UTC, Julian702 requested changes
Seems to work as far as I tested it, just found one problem:

- endpoint `/api/groups/:groupID/decks` returns an empty string as `groupID`for every deck

2023-11-28 08:26 UTC, TomRomeo commented on backend/api-documentation/decks/copy deck.bru
> +  seq: 9
changed in 22ef430

2023-11-28 08:26 UTC, TomRomeo commented on backend/api-documentation/decks/copy deck.bru
> +      "deckName": "test group"
changed in 22ef430

2023-11-28 08:27 UTC, TomRomeo commented on backend/api-documentation/decks/copy deck.bru
> +}
changed in 22ef430

2023-11-28 10:21 UTC, Julian702 commented on backend/api-documentation/decks/copy deck.bru
> +  seq: 9
its not changed

2023-11-28 10:46 UTC, Julian702 approved these changes

2023-11-28 10:48 UTC, merged