Add i18n
kioku-project/kioku pull request #167
Opened 2023-11-08 11:14 UTC by TomRomeo

# Internationalization of Kioku

This PR implements i18n for Kioku.
The policy will be that every component has to be created with English text in the source code but German translations will have to be provided.

To internationalize, we will use a mixture of NextJS’s native capability for [internationalized routing](https://nextjs.org/docs/pages/building-your-application/routing/internationalization) in conjunction with the translation library [Lingui](https://lingui.dev/).

## NextJS’s native internationalized routing.
NextJS natively supports internationalised routing. This means that it understands `/de/home` is asking for the `home` page with German text. Furthermore, all navigation using Next’s `Link` component and the `useRouter()` hook will automatically adjust the paths in order to keep the correct language for a user.

## Lingui
Lingui is a translation library that offers various macros to ease the process of translating such as plural handling and conditionals. The following section will briefly explain the most important concepts of Lingui:

### The `<Trans>` macro

The `<Trans>` macro will most probably be used the often when you want to create an internationalised component
```jsx
import { Trans } from "@lingui/macro";

function render() {
  return (
    <>
      <h1>
        <Trans>LinguiJS example</Trans>
      </h1>
      <p>
        <Trans>
          Hello <a href="/profile">{name}</a>.
        </Trans>
      </p>
    </>
  );
}
```
By simply wrapping text inside of components with the `<Trans>` macro, the text will be automatically recognized as translatable text.

## The `useLingui()` macro

It is not always possible to wrap text inside of components with the `<Trans>` tag. Take for example this situation, where you want to pass a string as a property to a component:
```jsx
import { msg } from "@lingui/macro";
import { useLingui } from "@lingui/react";

export default function ImageWithCaption() {
  const { _ } = useLingui();

  return <img src="..." alt={_(msg`Image caption`)} />;
}
```
Here, we want to be able to translate the image caption but we can’t use the `<Trans>` tag in the `alt` property so we have to do it like this.

## Translate outside of React components
import { t } from "@lingui/macro";

export function showAlert() {
  alert(t`...`);
}

## Plural
With Lingui, it is also easy to work pluralization into the frontend text. Plural text can be defined like this and the correct text will automatically be selected depending on the number.
plural(numBooks, {
  one: "# book",
  other: "# books",
});

# Extraction and Compilation
After developing new components, you will have to generate the translation files using `npm run extract`.
After that, the new source texts will be automatically added to `locale/de/messages.po`. You can search for the new texts and translate them inside of this file.
Finally, run `npm run compile` to compile the translations into Typescript files that can be used by the frontend.

—

This was only a short introduction. If you want to learn more about Lingui, check out their [documentation](https://lingui.dev/tutorials/react-patterns)!

2023-11-08 12:00 UTC, JJthere approved these changes

2023-11-08 18:00 UTC, Julian702 commented on frontend/locales/de/messages.po
> +msgstr "Starte Deine Lernreise noch heute mit Kioku - der cloudbasierten Lernkartenanwendung, die sich auf die kollaborative Erstellung von Lerninhalten spezialisiert hat."
Maybe we can also find another word for 'Lernreise'?
```suggestion
msgstr "Starte Deine Lernreise noch heute mit Kioku - der cloudbasierten Karteikarten-Anwendung, die sich auf die kollaborative Erstellung von Lerninhalten konzentriert."
```

2023-11-08 18:00 UTC, Julian702 commented on frontend/locales/de/messages.po
> +msgstr "Benutzer geändert!"
```suggestion
msgstr "Benutzer aktualisiert!"
```

2023-11-08 18:05 UTC, Julian702 commented on frontend/locales/de/messages.po
> +msgstr "\"Wir liefern Dir detaillierte Statistiken und Einblicke in Deinen Studienfortschritt. Ermittle Verbesserungsmöglichkeiten, um Deine Strategie für maximale Effektivität zu optimieren!"
Is there any reason for `\"`

```suggestion
msgstr "Wir stellen Dir detaillierte Statistiken und Einblicke in Deinen Studienfortschritt zur Verfügung. Finde Bereiche mit Verbesserungspotenzial, um Deine Strategie für maximale Effektivität zu optimieren!"
```

2023-11-08 18:11 UTC, Julian702 commented on frontend/locales/de/messages.po
> +msgstr "Willkommen bei Kioku - der cloudbasierten Karteikartenanwendung, die sich auf die gemeinsame Erstellung von Lerninhalten konzentriert. Unsere innovative Plattform ermöglicht es Dir, Dein Wiss
```suggestion
msgstr "Willkommen bei Kioku - der cloudbasierten Karteikarten-Anwendung, die sich auf die gemeinsame Erstellung von Lerninhalten konzentriert. Unsere innovative Plattform ermöglicht es Dir, Dein Wissen auf Karteikarten zu organisieren und diese mit anderen Nutzern zu teilen, um Dein Wissen auf die nächste Stufe zu heben. Melde Dich noch heute bei Kioku an und erlebe die Zukunft des Lernens."
```

2023-11-08 18:14 UTC, Julian702 commented on frontend/locales/de/messages.po
> +msgstr "Falscher Username oder Passwort"
```suggestion
msgstr "Falscher Benutzername oder falsches Passwort"
```

2023-11-08 18:15 UTC, Julian702 commented on frontend/locales/de/messages.po
> +msgstr "Du hast es geschafft! Für heute sind keine weiteren Karten zu lernen."
```suggestion
msgstr "Du hast es geschafft! Für heute gibt es keine Karten mehr zu lernen."
```

2023-11-08 18:16 UTC, Julian702 commented on frontend/locales/de/messages.po
> +msgstr "Du musst wieder eingeladen oder deine Anfrage angenommen werden."
```suggestion
msgstr "Du musst eingeladen werden oder eine Anfrage stellen, um der  Gruppe erneut beitreten zu können."
```

2023-11-08 18:26 UTC, Julian702 commented on frontend/pages/_app.tsx
> +		console.log(messages);
Remove `console.log`
```suggestion
```

2023-11-08 18:30 UTC, Julian702 commented on package-lock.json
> +}
This file isn't intended, is it?

2023-11-09 21:10 UTC, TomRomeo commented on package-lock.json
> +}
it can actually be deleted (lol)

2023-11-09 21:11 UTC, TomRomeo commented on frontend/pages/_app.tsx
> +		console.log(messages);
implemente in fb280a

2023-11-09 21:11 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Du musst wieder eingeladen oder deine Anfrage angenommen werden."
changed in fb280a

2023-11-09 21:11 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Du hast es geschafft! Für heute sind keine weiteren Karten zu lernen."
changed in fb280a

2023-11-09 21:11 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Falscher Username oder Passwort"
changed in fb280a

2023-11-09 21:12 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Willkommen bei Kioku - der cloudbasierten Karteikartenanwendung, die sich auf die gemeinsame Erstellung von Lerninhalten konzentriert. Unsere innovative Plattform ermöglicht es Dir, Dein Wiss
changed in ffb280a

2023-11-09 21:13 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "\"Wir liefern Dir detaillierte Statistiken und Einblicke in Deinen Studienfortschritt. Ermittle Verbesserungsmöglichkeiten, um Deine Strategie für maximale Effektivität zu optimieren!"
changed in ffb280a

2023-11-09 21:13 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Benutzer geändert!"
changed in ffb280a

2023-11-09 21:13 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Starte Deine Lernreise noch heute mit Kioku - der cloudbasierten Lernkartenanwendung, die sich auf die kollaborative Erstellung von Lerninhalten spezialisiert hat."
changed in ffb280a

2023-11-09 21:13 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Logge Dich mit Deinem Account ein"
changed in ffb280a

2023-11-09 21:13 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Anfrage senden!"
changed in ffb280a

2023-11-09 21:13 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Wiederhole Passwort"
changed in ffb280a

2023-11-09 21:14 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Keine Stapel in Gruppe"
changed in ffb280a

2023-11-09 21:14 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Kioku ist mit Anki kompatibel, so dass du deine bestehenden Decks in unsere Anwendung importieren und auch exportieren kannst, während du die Vorteile der kollaborativen Funktionen von Kioku
changed in ffb280a

2023-11-09 21:14 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Gruppe geändert!"
changed in ffb280a

2023-11-09 21:14 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Stapel Name"
changed in ffb280a

2023-11-09 21:14 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Leg los"
changed in ffb280a

2023-11-09 21:14 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Jeder muss eingeladen werden um der Gruppe beizutreten"
changed in ffb280a

2023-11-09 21:14 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Lösche Stapel"
changed in ffb280a

2023-11-09 21:15 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Lösche Account"
changed in ffb280a

2023-11-09 21:15 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Stapel geändert!"
changed in ffb280a

2023-11-09 21:15 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Neuer Stapel"
changed in ffb280a

2023-11-09 21:15 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Erstelle und individualisiere deine eigenen Karteikarten, genau nach deinen Bedürfnissen und Präferenzen. Lege dein eigenes Tempo mit unserem Spaced Repetition System fest, um dein Potenzial
changed in ffb280a

2023-11-09 21:15 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Arbeite mit deinen Freunden und Kommilitonen in Gruppen zusammen und bearbeite gemeinsame Decks. Lernt gemeinsam und motiviert euch gegenseitig!"
changed in ffb280a

2023-11-09 21:15 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgid "Click Again"
changed in ffb280a

2023-11-09 21:15 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Klicke nochmal"
changed in ffb280a

2023-11-09 21:16 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Ändere, wie andere der Gruppe beitreten können"
changed in ffb280a

2023-11-09 21:16 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Karten gelernt"
changed in ffb280a

2023-11-09 21:16 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Karte aktualisieren!"
changed in ffb280a

2023-11-09 21:16 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Erfolge und Ranglisten machen das Lernen noch interessanter und motivierender. Kioku hilft Dir, bessere Ergebnisse zu erzielen und Deine persönlichen Lernziele zu realisieren!"
changed in ffb280a

2023-11-09 21:16 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Lösche Gruppe"
changed in ffb280a

2023-11-09 21:22 UTC, TomRomeo commented on frontend/components/deck/Deck.tsx
> +			toast.info(_(msg`Deck created!`), { toastId: "newDeckToast" });
mh, according to the [documentation](https://lingui.dev/tutorials/react-patterns#translations-outside-react-components) this should not work / is not recommmended. Therefore, I changed this in 2b3bd60

2023-11-09 21:29 UTC, TomRomeo commented on docs/frontend_development.md
> +- [Internationalization](#internationalization)
ok.

2023-11-09 21:30 UTC, TomRomeo commented on docs/frontend_development.md
> +NextJS natively supports internationalised routing. This means that it understands `/de/home` is asking for the `home` page with German text. Furthermore, all navigation using Next’s `Link` component
implemented in 85fcc73

2023-11-09 21:30 UTC, TomRomeo commented on docs/frontend_development.md
> +# Internationalization
implemented in 85fcc73

2023-11-09 21:30 UTC, TomRomeo commented on docs/frontend_development.md
> +To internationalize Kioku in different languages, we use NextJS's native capability for [internationalized routing](https://nextjs.org/docs/pages/building-your-application/routing/internationalizatio
implemented in 85fcc73

2023-11-09 21:31 UTC, TomRomeo commented on docs/frontend_development.md
> +## NextJS’s native internationalised routing.
implemented in 85fcc73

2023-11-09 21:31 UTC, TomRomeo commented on docs/frontend_development.md
> +## Lingui
implemented in 85fcc73

2023-11-09 21:31 UTC, TomRomeo commented on docs/frontend_development.md
> +### The `<Trans>` macro
implemented in 85fcc73

2023-11-09 21:31 UTC, TomRomeo commented on docs/frontend_development.md
> +The `<Trans>` macro will most probably be used the often when you want to create an internationalised component
implemented in85fcc73

2023-11-09 21:31 UTC, TomRomeo commented on docs/frontend_development.md
> +### The `useLingui()` macro
implemented in85fcc73

2023-11-09 21:32 UTC, TomRomeo commented on docs/frontend_development.md
> +### Translate outside of React components
implemented in 85fcc73

2023-11-09 21:32 UTC, TomRomeo commented on docs/frontend_development.md
> +If you want to translat texts that resides in functions that are not React components, you can not use the `<Trans>` tag and `useLingui()` hook, instead you will have to use the `t` macro.
implemented in 85fcc73

2023-11-09 21:32 UTC, TomRomeo commented on docs/frontend_development.md
> +### Plural
implemented in 85fcc73

2023-11-09 21:32 UTC, TomRomeo commented on docs/frontend_development.md
> +});
done in 85fcc73

2023-11-09 21:33 UTC, TomRomeo commented on docs/frontend_development.md
> +### Extraction and Compilation
implemented in 85fcc73

2023-11-09 21:33 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "{dueCards, plural, one {# Karte übrig} other {# Karten übrig}}"
implemented in ffb280a

2023-11-09 21:34 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Greife von überall und jederzeit auf deine Karteikarten zu. Wechsle nahtlos zwischen verschiedenen Plattformen und verpasse nie wieder eine Lerngelegenheit!"
implemented in ffb280a

2023-11-09 21:34 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Kioku ist mit Anki kompatibel, so dass du deine bestehenden Decks in unsere Anwendung importieren und auch exportieren kannst, während du die Vorteile der kollaborativen Funktionen von Kioku
implemented in ffb280a

2023-11-09 21:34 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Nachdem du deinen Benutzer gelöscht hast, gibt es kein Zurück mehr."
implementedi n ffb280a

2023-11-09 21:34 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Nachdem du die Gruppe gelöscht hast, gibt es kein Zurück mehr."
implemented in ffb280a

2023-11-09 21:35 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Nachdem du den Stapel gelöscht hast, gibt es kein Zurück mehr."
implemented in ffb280a

2023-11-09 21:35 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Willkommen bei Kioku - der cloudbasierten Karteikartenanwendung, die sich auf die gemeinsame Erstellung von Lerninhalten konzentriert. Unsere innovative Plattform ermöglicht es Dir, Dein Wiss
implemented in ffb280a

2023-11-09 21:36 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Arbeite mit deinen Freunden und Kommilitonen in Gruppen zusammen und bearbeite gemeinsame Decks. Lernt gemeinsam und motiviert euch gegenseitig!"
implemented in ffb280a

2023-11-09 21:36 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Erstelle und individualisiere deine eigenen Karteikarten, genau nach deinen Bedürfnissen und Präferenzen. Lege dein eigenes Tempo mit unserem Spaced Repetition System fest, um dein Potenzial
implemented in ffb280a

2023-11-10 08:44 UTC, Julian702 approved these changes

2023-11-10 13:19 UTC, JJthere approved these changes

2023-11-10 21:24 UTC, memeToasty requested changes

2023-11-10 21:24 UTC, memeToasty commented on frontend/locales/de/messages.po
> +msgstr "Gruppe Löschen"
```suggestion
msgstr "Gruppe löschen"
```

2023-11-10 21:24 UTC, memeToasty commented on frontend/locales/de/messages.po
> +msgstr "Nochmal Klicken"
```suggestion
msgstr "Nochmal klicken"
```

2023-11-10 21:35 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Gruppe Löschen"
fixed in 54d8fcd

2023-11-10 21:35 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Nochmal Klicken"
fixed in 54d8fcd

2023-11-10 23:09 UTC, darmiel commented on frontend/locales/de/messages.po
> +msgstr "Bitte einen validen {type} eingeben."
```suggestion
msgstr "Bitte einen gültigen {type} eingeben."
```

2023-11-10 23:09 UTC, darmiel commented on frontend/locales/de/messages.po
> +msgstr "Angrage gesendet!"
```suggestion
msgstr "Anfrage gesendet!"
```

2023-11-10 23:09 UTC, darmiel commented on frontend/locales/de/messages.po
> +msgstr "Benutzer"
(also ff)
I think `Nutzer` sounds more friendly, `Benutzer` is a bit too formal for Kioku's  informal tone

2023-11-10 23:09 UTC, darmiel commented on frontend/locales/de/messages.po
> +msgstr "Wir revolutionieren wie Menschen lernen."
```suggestion
msgstr "Wir revolutionieren, Menschen lernen."
```

2023-11-10 23:09 UTC, darmiel commented on frontend/locales/de/messages.po
> +msgstr "Du musst eingeladen werden oder eine Anfrage stellen, um der  Gruppe erneut beitreten zu können."
```suggestion
msgstr "Du musst eingeladen werden oder eine Anfrage stellen, um der Gruppe erneut beitreten zu können."
```

2023-11-11 13:24 UTC, TomRomeo commented on docs/frontend_development.md
> +### NextJS’s native internationalized routing.
changed in 439e3a7

2023-11-11 13:24 UTC, TomRomeo commented on docs/frontend_development.md
> +### Lingui
changed in 439e3a7

2023-11-11 13:24 UTC, TomRomeo commented on docs/frontend_development.md
> +To internationalize Kioku in different languages, we use NextJS's native capability for [internationalized routing](https://nextjs.org/docs/pages/building-your-application/routing/internationalizatio
changed in 439e3a7

2023-11-11 13:24 UTC, TomRomeo commented on docs/frontend_development.md
> +NextJS natively supports internationalized routing. This means that it understands `/de/home` is asking for the `home` page with German text. Furthermore, all navigation using Next’s `Link` component
changed in 439e3a7

2023-11-11 13:24 UTC, TomRomeo commented on docs/frontend_development.md
> +Lingui is a translation library that offers various macros to ease the process of translating such as plural handling and conditionals. The following section will briefly explain the most important c
changed in 439e3a7

2023-11-11 13:25 UTC, TomRomeo commented on docs/frontend_development.md
> +It is not always possible to wrap text inside of components with the `<Trans>` tag. Take for example this situation, where you want to pass a string as a property to a component:
changed in 439e3a7

2023-11-11 13:25 UTC, TomRomeo commented on docs/frontend_development.md
> +Here, we want to be able to translate the image caption but we can’t use the `<Trans>` tag in the `alt` property so we have to do it like this.
changed in 439e3a7

2023-11-11 13:25 UTC, TomRomeo commented on docs/frontend_development.md
> +If you want to translate texts that reside in functions that are not React components, you can not use the `<Trans>` tag and the `useLingui()` hook, instead you will have to use the `t` macro.
changed in 439e3a7

2023-11-11 13:25 UTC, TomRomeo commented on docs/frontend_development.md
> +With Lingui, it is also easy to work pluralization into the frontend text. Plural text can be defined like this and the correct text will automatically be selected depending on the number.
changed in 439e3a7

2023-11-11 13:25 UTC, TomRomeo commented on frontend/components/navigation/Navbar.tsx
> +					<Trans>Login</Trans>{" "}
removed in 439e3a7

2023-11-11 13:26 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Zurück zum Stapel!"
@Julian702 and I decided that we will keep `Stapel` as the German translation for `Deck`.

2023-11-11 13:26 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "{0, plural, one {Du musst eine Karte} other {Du musst # Karten}}"
changed in 439e3a7

2023-11-11 13:26 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Wilkommen, {0}"
changed in 439e3a7

2023-11-11 13:27 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Kioku ist mit Anki kompatibel, sodass Du Deine bestehenden Decks in unsere Anwendung importieren und auch wieder exportieren kannst, während Du die Vorteile der kollaborativen Funktionen von
changed to `Stapel` in 439e3a7 😊

2023-11-11 13:27 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Hit Rate"
changed in 439e3a7

2023-11-11 13:27 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Benutzer eingeladen!"
changed in 439e3a7

2023-11-11 13:27 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Gratulation!"
changed in 439e3a7

2023-11-11 13:29 UTC, TomRomeo commented on frontend/components/navigation/Tabs/GroupSettingsTab.tsx
> +							: _(msg`"Delete Group`)
removed in 439e3a7

2023-11-11 13:29 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgid "\"Delete Group"
changed in 3fcd8a1

2023-11-11 13:29 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Entdecke Kioku's einzigartige Features"
changed in 439e3a7

2023-11-11 13:29 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Email"
changed in 439e3a7

2023-11-11 13:30 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Jeder kann anfragen dieser Gruppe beizutreten"
changed in 439e3a7

2023-11-11 13:30 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Benutzer mit Email einladen"
changed in 439e3a7

2023-11-11 13:30 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Bitte einen validen {type} eingeben."
changed in 439e3a7

2023-11-11 13:30 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Angrage gesendet!"
changed in 439e3a7

2023-11-11 13:31 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Benutzer"
@Julian702 and I decided to stay with `Benutzer` because we think it sounds better.

2023-11-11 13:31 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Wir revolutionieren wie Menschen lernen."
changed in 439e3a7

2023-11-11 13:31 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Du musst eingeladen werden oder eine Anfrage stellen, um der  Gruppe erneut beitreten zu können."
changed in 439e3a7

2023-11-11 14:19 UTC, darmiel approved these changes

2023-11-11 14:19 UTC, darmiel commented on docs/frontend_development.md
> +To internationalize Kioku in different languages, we use NextJS's native capability for [internationalized routing](https://nextjs.org/docs/pages/building-your-application/routing/internationalizatio
```suggestion
To internationalize Kioku in different languages, we use Next.js's native capability for [internationalized routing](https://nextjs.org/docs/pages/building-your-application/routing/internationalization) as well as the [Lingui](https://lingui.dev/) library. Our current policy is that English is the default language and a German translation for all texts has to be provided. However, if you would like to add another language, contributions are always welcome!
```

2023-11-11 14:19 UTC, darmiel commented on docs/frontend_development.md
> +### NextJS’s native internationalized routing.
```suggestion
### Next.js’s native internationalized routing.
```

2023-11-11 14:25 UTC, memeToasty approved these changes

2023-11-11 16:41 UTC, TomRomeo commented on docs/frontend_development.md
> +To internationalize Kioku in different languages, we use NextJS's native capability for [internationalized routing](https://nextjs.org/docs/pages/building-your-application/routing/internationalizatio
fixed in 5cfc1b2

2023-11-11 16:42 UTC, TomRomeo commented on docs/frontend_development.md
> +### NextJS’s native internationalized routing.
fixed in 5cfc1b2

2023-11-12 10:32 UTC, 4KevR requested changes

2023-11-12 10:32 UTC, 4KevR commented on frontend/.storybook/main.ts
> +        		},
strange format

2023-11-12 10:32 UTC, 4KevR commented on frontend/.swcrc
> +}
wrong tab width

2023-11-12 10:32 UTC, 4KevR commented on frontend/locales/de/messages.d.ts
> +          export { messages };
strange format

2023-11-12 10:32 UTC, 4KevR commented on frontend/locales/de/messages.po
> +msgstr "Ändere, wie Andere der Gruppe beitreten können"
```suggestion
msgstr "Ändere, wie andere der Gruppe beitreten können"
```

2023-11-12 10:32 UTC, 4KevR commented on frontend/locales/en/messages.d.ts
> +          export { messages };
s.a (or is this automatically generated?)

2023-11-12 10:53 UTC, TomRomeo commented on frontend/locales/de/messages.d.ts
> +          export { messages };
yes, these files are automatically generated.

2023-11-12 10:54 UTC, TomRomeo commented on frontend/locales/en/messages.d.ts
> +          export { messages };
s.a, automatically generated

2023-11-12 10:55 UTC, TomRomeo commented on frontend/locales/de/messages.po
> +msgstr "Ändere, wie Andere der Gruppe beitreten können"
fixed in 6c2ee18

2023-11-12 10:55 UTC, TomRomeo commented on frontend/.swcrc
> +}
fixed in 6c2ee18

2023-11-12 10:55 UTC, TomRomeo commented on frontend/.storybook/main.ts
> +        		},
fixed in 6c2ee18

2023-11-12 11:05 UTC, 4KevR approved these changes

2023-11-12 11:06 UTC, merged