Backend migration to go-micro
kioku-project/kioku pull request #18
Opened 2023-04-25 15:46 UTC by 4KevR

This PR implements the backend migration to go-micro to facilitate service development in the context of our application. The central work of this PR includes

- Migration of `loginservice` and `registerservice` to go-micro
- Interface abstraction of our database operations to enable DB independent implementations of our service code
- Set-up of Envoy as a proxy for JSON to gRPC transcoding (production setup pending)
- Added Envoy as a proxy in Next.js
- Added instructions on how to create new services

2023-04-26 07:14 UTC, TomRomeo requested changes
Very great work! I just have some minor nits 😊

2023-04-26 07:14 UTC, TomRomeo commented on backend/README.md
> +        go-micro new service --health --kubernetes github.com/kioku-project/kioku/services/<name-of-new-service>
```suggestion
        go-micro new service --health --kubernetes github.com/kioku-project/kioku/<name-of-new-service>
```
Shouldn't the command look like this? I think the cli adds the /services/ subpath automatically.

2023-04-26 07:14 UTC, TomRomeo commented on backend/README.md
> +Additionally, you need to set up the `protoc` compiler in your environment. See [here](https://grpc.io/docs/protoc-installation/) for installation instructions according to your system.
If you like, you can also talk about `make` as a dependency. For Windows it has to be installed explicitly and the easiest way I have found is to use Chocolatey for that.

2023-04-26 07:14 UTC, TomRomeo commented on backend/store/store.go
I think we should discuss if this double abstraction is really necessary. I don't think it is very maintainable to add functions for many different queries. Since we decided on using postgreSQL we could also initialize the services with gorm directly.
What is your opinion on that?

2023-04-26 07:41 UTC, 4KevR commented on backend/README.md
> +        go-micro new service --health --kubernetes github.com/kioku-project/kioku/services/<name-of-new-service>
The command should be right as it is stated here, the cli doesn't add the /services/ subpath at the moment. We could discuss whether we want to change this behavior.

2023-04-26 07:56 UTC, 4KevR commented on backend/store/store.go
I personally like the abstraction as we are very flexible in the future on how we want to implement the database layer of our application although we have decided to use PostgreSQL at the moment. It also makes our handler code more readable in my opinion as different database operations are factorized in the implementation of the store interface and are therefore structured by task. We could further assess whether this abstraction generates more overhead than use for our project and then decide on the handling of the database operations.

2023-04-26 08:27 UTC, 4KevR commented on backend/services/loginservice/handler/loginservice.go
> +	return errors.New("This email or password is wrong")
Added in commit de223af6e516e7930354d13ea391e5011f385ca7

2023-04-26 08:28 UTC, 4KevR commented on backend/services/registerservice/handler/registerservice.go
> +
Added in commit de223af6e516e7930354d13ea391e5011f385ca7

2023-04-26 08:28 UTC, 4KevR commented on .gitignore
> +*.pb
Added in commit de223af6e516e7930354d13ea391e5011f385ca7

2023-04-26 08:28 UTC, 4KevR commented on backend/README.md
> +Additionally, you need to set up the `protoc` compiler in your environment. See [here](https://grpc.io/docs/protoc-installation/) for installation instructions according to your system.
Added in commit de223af6e516e7930354d13ea391e5011f385ca7

2023-04-27 07:03 UTC, TomRomeo commented
Also, what do you think about renaming the services from `registerservice` and `loginservice` to just `register` and `login`? That way the paths would be cleaner, e.g. `backend/services/register/...` and the name of Go types would not contain duplicates, e.g. `LoginserviceService`.

2023-04-30 11:18 UTC, 4KevR commented
> Also, what do you think about renaming the services from `registerservice` and `loginservice` to just `register` and `login`? That way the paths would be cleaner, e.g. `backend/services/register/...` and the name of Go types would not contain duplicates, e.g. `LoginserviceService`.

Updated naming in 860e441b88851496e0841f4a6618e27e1ab7f58f

2023-05-01 16:58 UTC, 4KevR commented
The last commits removed the requirement to use envoy as a proxy for our backend architecture. Now, there is a new frontend service, which acts as a proxy for the gRPC services. It exposes an http server made with fiber and implements the required handlers for the endpoints `/api/login` and `/api/register`.

2023-05-03 07:51 UTC, TomRomeo reviewed
Looks very promising, I just notices some minor things:

2023-05-03 07:51 UTC, TomRomeo commented on backend/services/frontend/main.go
> +	// }
remove comment
```suggestion

```

2023-05-03 07:51 UTC, TomRomeo commented on backend/services/frontend/handler/frontend.go
> +	}
Maybe we could simplify parameter validation with fiber's built in validation. ([link](https://docs.gofiber.io/guide/validation/))
We could then cast data to the preferred type (eg. model.User) instead of a string map and stop using this validation pattern everywhere.

2023-05-03 07:51 UTC, TomRomeo commented on backend/services/frontend/handler/frontend.go
> +	}
same validation idea as above

2023-05-03 19:22 UTC, 4KevR commented on backend/services/frontend/main.go
> +	// }
Removed in ec5d41931435837104a82253ce06790d0d4df073

2023-05-03 19:27 UTC, 4KevR commented on backend/services/frontend/handler/frontend.go
> +	}
Good idea, let's cover this in another pull request as we need to think about the exact implementation of a mapper. Because the validation from Fiber will lead to issues regarding the relevance of certain fields in specific requests targeting the same object (e.g. the user object in register and also login).

2023-05-03 19:27 UTC, 4KevR commented on backend/services/frontend/handler/frontend.go
> +	}
same explanation as above

2023-05-04 06:55 UTC, TomRomeo approved these changes

2023-05-04 06:57 UTC, memeToasty approved these changes

2023-05-04 08:07 UTC, Julian702 approved these changes
LGTM 👍

2023-05-04 08:12 UTC, merged