Redesign deck component
kioku-project/kioku pull request #188
Opened 2023-11-22 09:36 UTC by Julian702

## Description

This pr implements the redesigned deck component. Note that the input field to create new decks is a temporary solution and will be replaced with a search bar when the modal for creating decks is implemented.

2023-11-22 09:36 UTC, darmiel commented
Please remove the border on hover 😊

2023-11-22 21:05 UTC, darmiel requested changes

2023-11-23 13:41 UTC, Julian702 commented on frontend/components/deck/Deck.tsx
> +						className="font-black text-[#7B100E]"
Good idea, but I think the dark red color looks much better. Since we have to think about changing the color dynamically at all, I would leave it as it is for now.

2023-11-23 13:41 UTC, Julian702 commented on frontend/components/deck/Deck.tsx
> +								/>
?

2023-11-23 13:43 UTC, Julian702 commented on frontend/components/deck/DeckList.tsx
>  					onClick={() => router.push(`/group/${group.groupID}`)}
Because this is a custom component here. We should consider to change this in the whole project in another pr.

2023-11-23 13:54 UTC, darmiel commented on frontend/components/deck/Deck.tsx
> +								/>
🧑‍🦯

2023-11-23 13:55 UTC, darmiel commented on frontend/components/deck/Deck.tsx
> +						className="font-black text-[#7B100E]"
Is there already an issue for this? Otherwise I'll leave this open to not forgot about it

2023-11-23 15:40 UTC, Julian702 commented on frontend/components/deck/DeckList.tsx
>  					onClick={() => router.push(`/group/${group.groupID}`)}
Added this to the backlog in #143

2023-11-23 16:34 UTC, darmiel commented on frontend/components/deck/Deck.tsx
>  				}
nit: I've seen this multiple times so far, consider exporting this callback somewhere, e. g.

```ts
export const clickOnEnterKeyEvent = (event: KeyEvent) => event.key === "Enter" && event.target.dispatchEvent(
  new Event("click", { bubbles: true })
);
```

2023-11-23 16:34 UTC, darmiel commented on frontend/components/deck/Deck.tsx
> +							>
you should change the button component:
- add `href` attribute
- if `href` passed, return `next/link`, otherwise `button`

advantages:
- Prefetching
- Accessibility (expected semantics for links)

feel free to create an issue for this if you don't want to do this in this PR :)

2023-11-23 16:34 UTC, darmiel commented on frontend/components/graphics/Icon.tsx
I think this component will significantly increase the bundle size because every icon will be loaded. Maybe test if this affects the bundle size

2023-11-23 19:14 UTC, Julian702 commented on frontend/components/deck/Deck.tsx
> +							>
its included in #143

2023-11-23 19:16 UTC, Julian702 commented on frontend/components/graphics/Icon.tsx
We will try to avoid to use this component, when we have static Icons but when they are set dynamically we have to do it this way.

2023-11-23 19:17 UTC, Julian702 commented on frontend/components/deck/Deck.tsx
>  				}
its included in #143

2023-11-24 07:27 UTC, memeToasty approved these changes

2023-11-24 08:11 UTC, 4KevR approved these changes

2023-11-24 08:11 UTC, 4KevR commented on frontend/locales/en/messages.po
> +msgstr "Create New Deck"
```suggestion
#: components/navigation/Tabs/DecksTab.tsx:41
msgid "Create new Deck"
msgstr "Create new Deck"
```

2023-11-24 12:03 UTC, TomRomeo approved these changes

2023-11-24 17:37 UTC, merged