Add new login page design
kioku-project/kioku pull request #195
Opened 2023-11-27 13:33 UTC by Julian702

## Description

This pr implements the new login page. Huge thanks to @darmiel for the amazing design <3

2023-11-27 13:48 UTC, memeToasty approved these changes

2023-11-27 15:18 UTC, TomRomeo approved these changes
🫶🏻

2023-11-28 08:44 UTC, darmiel commented on frontend/pages/login.tsx
> +								<a
```suggestion
								<button
```

2023-11-28 08:44 UTC, darmiel commented on frontend/pages/login.tsx
> +										}
I think you introduced a function for this a few PRs ago

2023-11-28 08:44 UTC, darmiel commented on frontend/pages/login.tsx
> +										<Trans>Sign up now!</Trans>
```suggestion
										<Trans>Sign Up now!</Trans>
```

2023-11-28 08:44 UTC, darmiel commented on frontend/pages/login.tsx
> +										<Trans>Sign in now!</Trans>
```suggestion
										<Trans>Sign In now!</Trans>
```

2023-11-28 08:44 UTC, darmiel commented on frontend/pages/login.tsx
> +									buttonIcon="ArrowRight"
why pass the icon as a string?

2023-11-28 08:44 UTC, darmiel commented on frontend/pages/login.tsx
> +										</div>
extract into local component

2023-11-28 08:44 UTC, darmiel commented on frontend/pages/login.tsx
> +								{!login && (
these can be me<>rged</>

2023-11-28 08:44 UTC, darmiel commented on frontend/pages/login.tsx
> +									router.push("/home");
use `next/link`

2023-11-28 09:17 UTC, Julian702 commented on frontend/pages/login.tsx
> +										}
No, it's still in our backlog and will be implemented in a future pr.

2023-11-28 09:39 UTC, Julian702 commented on frontend/pages/login.tsx
> +									router.push("/home");
It's already part of the backlog (#197)

2023-11-28 09:46 UTC, Julian702 commented on frontend/pages/login.tsx
> +										<Trans>Sign up now!</Trans>
@4KevR and I would prefer the lowercase variant.

2023-11-28 09:46 UTC, 4KevR requested changes
Great work!

2023-11-28 09:46 UTC, 4KevR commented on frontend/pages/login.tsx
> +										}
Maybe refactor to either delete the promise resolution (I know Sonarcloud has a problem with this) or find another way to implement the logic separation.

2023-11-28 09:46 UTC, Julian702 commented on frontend/pages/login.tsx
> +										<Trans>Sign in now!</Trans>
s.a.

2023-11-28 10:06 UTC, Julian702 commented on frontend/pages/login.tsx
> +								<a
fixed in d6f6fb8dd2f10f19a56fb12858f2a7ffb318ef84

2023-11-28 10:07 UTC, Julian702 commented on frontend/pages/login.tsx
> +									buttonIcon="ArrowRight"
fixed in d6f6fb8dd2f10f19a56fb12858f2a7ffb318ef84

2023-11-28 10:09 UTC, Julian702 commented on frontend/pages/login.tsx
> +								{!login && (
fixed in d6f6fb8dd2f10f19a56fb12858f2a7ffb318ef84

2023-11-28 10:09 UTC, Julian702 commented on frontend/pages/login.tsx
> +										}
fixed in d6f6fb8dd2f10f19a56fb12858f2a7ffb318ef84

2023-11-28 10:19 UTC, 4KevR approved these changes

2023-11-28 10:48 UTC, darmiel commented on frontend/components/input/Button.tsx
> +	buttonText?: string;
this is horrible

2023-11-28 10:48 UTC, darmiel commented on frontend/pages/login.tsx
> +											: _(msg`Register`)
```suggestion
											: _(msg`Sign up`)
```

2023-11-28 10:48 UTC, darmiel commented on frontend/pages/login.tsx
> +									></ArrowRight>
```suggestion
									/>
```

2023-11-28 12:07 UTC, merged