Add dashboard tab
kioku-project/kioku pull request #202
Opened 2023-11-28 12:26 UTC by Julian702

## Description

This pr uses the changes from #200 to implement a first dashboard page with active and favorite decks.

2023-11-28 12:57 UTC, TomRomeo requested changes

2023-11-28 12:57 UTC, TomRomeo commented on frontend/types/Deck.ts
> +	favorite?: boolean;
Please rename to `isActive` and `isFavorite` again

2023-11-28 13:37 UTC, memeToasty approved these changes

2023-11-28 13:40 UTC, TomRomeo approved these changes

2023-11-28 17:12 UTC, 4KevR requested changes
Great job, see comments for small nits

2023-11-28 17:12 UTC, 4KevR commented on frontend/components/deck/Deck.tsx
> +	});
Dependencies of `useEffect` are not declared

2023-11-28 17:12 UTC, 4KevR commented on frontend/components/navigation/Tabs/DashboardTab.tsx
> +			<DeckList header={_(msg`Favorite Decks`)} decks={favoriteDecks} />
Either both decks capitalized or none of them

2023-11-29 07:30 UTC, Julian702 commented on frontend/components/deck/Deck.tsx
> +	});
fixed in 7c65439370d48f47cd0c3f4e2886b9a8ebff51d1

2023-11-29 07:30 UTC, Julian702 commented on frontend/components/navigation/Tabs/DashboardTab.tsx
> +			<DeckList header={_(msg`Favorite Decks`)} decks={favoriteDecks} />
fixed in 7c65439370d48f47cd0c3f4e2886b9a8ebff51d1

2023-11-29 07:49 UTC, 4KevR approved these changes

2023-11-29 07:49 UTC, merged