Add CreateDeckModal component
kioku-project/kioku pull request #215
Opened 2023-12-04 12:09 UTC by Julian702

## Description

This pr adds the CreateDeckModal component according to #193. The setting for public/private decks will be added later as soon as the SelectionField component is implemented.

## Screenshot
<img width="725" alt="Screenshot 2023-12-04 at 20 34 55" src="https://github.com/kioku-project/kioku/assets/66846059/7032967c-30c1-4502-bb00-c26495dad07c">

2023-12-04 19:29 UTC, memeToasty commented
![image](https://github.com/kioku-project/kioku/assets/31214870/ebcb1c35-6ed3-4184-afc8-46fe5716c126)

With this change implemented, wouldn't it be better to get rid of the entire grey bar, as only the "Plus"-Icon is clickable.
I don't have an immediate suggestion how to improve it, but it feels a bit odd this way

2023-12-04 21:18 UTC, Julian702 commented
> With this change implemented, wouldn't it be better to get rid of the entire grey bar, as only the "Plus"-Icon is clickable. I don't have an immediate suggestion how to improve it, but it feels a bit odd this way

As stated in #188 which implemented this area and temporary used it for the deck creation, the now free spaced resulting from moving the deck creation to the modal, will be used for a search bar in one of the nexts prs.

2023-12-05 07:43 UTC, memeToasty approved these changes
Thank you for this modal! :)

2023-12-05 07:58 UTC, TomRomeo requested changes

2023-12-05 07:58 UTC, TomRomeo commented on frontend/components/input/Button.tsx
> +			<Text className="" textSize={buttonTextSize}>
please remove the empty className attribute

2023-12-05 07:58 UTC, TomRomeo commented on frontend/components/modal/CreateDeckModal.tsx
> +				deckDescription: deckDescriptionInput.current?.value,
This might add null / undefined to the deck description if left empty.

2023-12-05 07:58 UTC, TomRomeo commented on frontend/components/modal/modal.tsx
> +} as const;
either populate or remove these.

2023-12-05 08:19 UTC, TomRomeo approved these changes

2023-12-05 22:03 UTC, 4KevR reviewed
Great feature, I just have a couple of comments.

2023-12-06 07:26 UTC, Julian702 commented on frontend/components/modal/modal.tsx
> +	header?: string;
Upsi, thanks for commenting!

2023-12-06 08:04 UTC, Julian702 commented on frontend/components/modal/modal.tsx
> +								<div className="relative w-full transform space-y-5 overflow-hidden rounded-t-lg bg-white p-5 text-left shadow-xl transition-all sm:max-w-xl sm:rounded-lg">
Nothing, I tried to animate the modal, but that has not worked.

2023-12-06 08:24 UTC, Julian702 commented on frontend/components/input/Button.tsx
> -	prefetch,
Yes

2023-12-06 08:24 UTC, Julian702 commented on frontend/locales/de/messages.po
> +msgstr "Stapel Namen eingeben"
fixed

2023-12-06 08:48 UTC, 4KevR approved these changes
Great!

2023-12-06 09:07 UTC, merged