Redesign mobile login page
kioku-project/kioku pull request #226
Opened 2024-01-10 08:21 UTC by Julian702

## Description

This pr redesigns the mobile login page. Have a look at the screenshot below.

![simulator_screenshot_4FDFCB32-4687-47A6-8BED-13286CB7D3E3](https://github.com/kioku-project/kioku/assets/66846059/53d5ead8-400c-4aa3-a167-5422d8864817)

2024-01-10 15:10 UTC, darmiel requested changes
please fix design issues (see figma)

2024-01-11 08:27 UTC, Julian702 commented on frontend/pages/login.tsx
> +								logoSize="reverse"
fixed in 9fa2cdc96a7325069730e8c02e86266eb8012a14

2024-01-11 08:29 UTC, Julian702 commented
> please fix design issues (see figma)

I fixed the color of the Icon in the Password InputField. If you want to see more changes, please be a little bit more specific.

2024-01-13 10:20 UTC, 4KevR commented on frontend/pages/login.tsx
> +									className="bg-[#ECECEC] p-3 text-base sm:text-xs"
Could it make sense to add this background color (#ECECEC) to our tailwind config? Maybe also alongside the text color (#B4B4B4) if we intend to use it more often. Not marking ff.

2024-01-16 13:06 UTC, memeToasty approved these changes

2024-01-17 13:37 UTC, Julian702 commented on frontend/pages/login.tsx
> +									className="bg-[#ECECEC] p-3 text-base sm:text-xs"
Of course you're right, we shouldn't use arbitrary values in the long term. However, since we don't have a new color scheme yet, I would refrain from including these values in our config. I think we should agree on a new color scheme first and then it is very easy to remove all these values.

2024-01-17 14:01 UTC, 4KevR commented on frontend/pages/login.tsx
> +									className="bg-[#ECECEC] p-3 text-base sm:text-xs"
Then I would suggest to first agree to a color scheme before merging this PR

2024-01-27 13:15 UTC, Julian702 commented on frontend/pages/login.tsx
> +									className="bg-[#ECECEC] p-3 text-base sm:text-xs"
Fixed in 87bec0998c1885bc8beb2b1726da62493afbb23c

2024-01-28 14:39 UTC, 4KevR approved these changes

2024-01-29 07:39 UTC, merged