Feature/frontend/action bar
kioku-project/kioku pull request #227
Opened 2024-01-10 13:54 UTC by Julian702

## Description

This pr implements an ActionBar on the Decks- and GroupsTab.

2024-01-13 10:51 UTC, 4KevR requested changes
Looks great, just small nits

2024-01-13 10:51 UTC, 4KevR commented on frontend/components/navigation/Tabs/DecksTab.tsx
> +				/>
Maybe you could extract the filtering part of the decks (`decks?.filter((deck) => deck.deckName.toUpperCase().includes(filter))`) to 
1. avoid code duplication
2. Resolve this illegal auto-formatting xD

2024-01-13 10:51 UTC, 4KevR commented on frontend/components/navigation/Tabs/GroupsTab.tsx
> +					}
Same here. Also, was it indented that the false block of the ternary does not include the optional chaining operator for groups?

2024-01-13 10:51 UTC, 4KevR commented on frontend/locales/de/messages.po
> +
I think I would rather go with `Gruppenbeschreibung` and `Gruppennamen` but up for discussion.

2024-01-13 10:51 UTC, 4KevR commented on frontend/locales/de/messages.po
> +msgstr "Gruppen Name"
s.a. to not forget if we change it

2024-01-16 13:14 UTC, memeToasty approved these changes

2024-02-01 16:58 UTC, 4KevR reviewed
I like the change! I have 2 comments for clarification.

2024-02-01 16:58 UTC, 4KevR commented on frontend/components/deck/DeckList.tsx
> +	const sortedDecks = reverse ? filteredDecks?.reverse() : filteredDecks;
`.reverse` lead to a SonarCloud issue. Maybe use `toReversed()` (non-mutating) instead.

2024-02-01 16:58 UTC, 4KevR commented on frontend/components/group/GroupList.tsx
> +	const sortedGroups = reverse ? filteredGroups?.reverse() : filteredGroups;
s.a.

And another idea. I am not a big React expert but could it make sense to use a `useMemo` here to wrap the filter and reverse operations?

2024-02-01 17:40 UTC, TomRomeo approved these changes

2024-02-01 17:40 UTC, TomRomeo commented on frontend/components/modal/CreateGroupModal.tsx
> +						label={_(msg`Group description`)}
```suggestion
						label={_(msg`Group Description`)}
```
I think we should use Title Case here, as we do with the group name as well.

2024-02-01 17:40 UTC, TomRomeo commented on frontend/components/navigation/Tabs/GroupSettingsTab.tsx
> +					header={_(msg`Group description`)}
If we decide to use Title Case as suggested above, we should change it here too.

2024-02-01 17:58 UTC, Julian702 commented on frontend/components/deck/DeckList.tsx
> +	const sortedDecks = reverse ? filteredDecks?.reverse() : filteredDecks;
Looks like `toReversed` is the more efficient solution to reverse an array.

2024-02-01 17:59 UTC, Julian702 commented on frontend/components/group/GroupList.tsx
> +	const sortedGroups = reverse ? filteredGroups?.reverse() : filteredGroups;
Yes, you are absolutely right. Thanks!

2024-02-01 18:00 UTC, Julian702 commented on frontend/components/modal/CreateGroupModal.tsx
> +						label={_(msg`Group description`)}
fixed in a39d1014ca5d856c1da2ee500c221e7f3503f244

2024-02-01 18:00 UTC, Julian702 commented on frontend/components/deck/DeckList.tsx
> +	const sortedDecks = reverse ? filteredDecks?.reverse() : filteredDecks;
fixed in a39d1014ca5d856c1da2ee500c221e7f3503f244

2024-02-01 18:00 UTC, Julian702 commented on frontend/components/navigation/Tabs/GroupSettingsTab.tsx
> +					header={_(msg`Group description`)}
fixed in a39d1014ca5d856c1da2ee500c221e7f3503f244

2024-02-01 20:34 UTC, 4KevR commented on frontend/components/deck/DeckList.tsx
> +	const sortedDecks = reverse ? filteredDecks?.reverse() : filteredDecks;
`toReversed` is new in ES2023. Our target definition of TS (tsconfig.json) is still on ES5 and our TS version does not include the ES2023 features via esnext in the lib definition. I think we would have to update to at least TS 5.2 to get the new functions. I think that's why the build is not working, but it is interesting that dev still works.

2024-02-02 10:07 UTC, Julian702 commented on frontend/components/deck/DeckList.tsx
> +	const sortedDecks = reverse ? filteredDecks?.reverse() : filteredDecks;
Ahh, thank for the tip! Now it's working :)

2024-02-02 12:29 UTC, 4KevR approved these changes

2024-02-02 12:32 UTC, merged