Fix path order in backend to enable the possibility to access invite/request paths
kioku-project/kioku pull request #230
Opened 2024-01-12 18:52 UTC by TomRomeo

## Description

This PR rearranges the paths in the backend api so the invite/request accept/decline endpoints are not overwritten.

## Resolved Issues
resolves #229

2024-01-12 19:36 UTC, Julian702 approved these changes

2024-01-13 12:20 UTC, 4KevR requested changes
Great, I just have two small nits.

2024-01-13 12:20 UTC, 4KevR commented on backend/services/frontend/main.go
> +	app.Delete("/api/groups/:groupID/members", svc.LeaveGroupHandler)
I think I would place these two endpoints at their old position (to kind of "introduce" the /members subpath). Also I think it would be beneficial to also reorder the handlers in the `frontend.go` so that they still represent the order of the endpoints here to keep it organized.

2024-01-14 13:19 UTC, Julian702 commented on backend/api-documentation/groups/decline invitation.bru
> +  name: decline invitation
No, the flip is on purpose. By sending a DELETE request to the /members/request endpoint, the invited user rejects this invitation. The other way around, the group rejects a request to join with a DELETE request to the /members/invitation endpoint.

2024-01-14 13:22 UTC, TomRomeo commented on backend/services/frontend/main.go
> +	app.Delete("/api/groups/:groupID/members", svc.LeaveGroupHandler)
I placed the two endpoints at the top again.
As the handlers are not ordered at the moment either, I would prefer to tackle the re-ordering in a separate refactoring PR.

2024-01-16 13:05 UTC, memeToasty approved these changes

2024-01-17 13:28 UTC, 4KevR commented on backend/services/frontend/main.go
> +	app.Delete("/api/groups/:groupID/members", svc.LeaveGroupHandler)
Created issue #234

2024-01-17 13:28 UTC, 4KevR approved these changes

2024-01-20 14:47 UTC, merged