Reworked starting page and added learning page
kioku-project/kioku pull request #26
Opened 2023-05-10 08:16 UTC by Julian702

2023-05-10 10:12 UTC, memeToasty approved these changes

2023-05-11 08:00 UTC, 4KevR requested changes
Very good, see comments for minor improvements

2023-05-11 08:00 UTC, 4KevR commented on frontend/components/deck/Deck.tsx
> +	id?: string;
Is there a reason that the deck id is optional? I think it would be beneficial to always encode an id into the deck attributes.

2023-05-11 08:00 UTC, 4KevR commented on frontend/components/deck/DeckOverview.tsx
> +	id?: string;
same as above

2023-05-11 08:00 UTC, 4KevR commented on frontend/components/navigation/Header.tsx
> +			)}
The behavior of this component is inconsistent on the `/home` and `/features` page. Please take a look at the placement styling.

2023-05-11 08:00 UTC, 4KevR commented on frontend/pages/login.tsx
> +		let name = document.querySelector("#name") as HTMLInputElement;
Is there a reason to not use `const`?

2023-05-11 08:56 UTC, Julian702 commented on frontend/components/navigation/Header.tsx
> +			)}
This behavior is due to the scrollbar. Not part of this PR. Will fix this later.

2023-05-11 09:10 UTC, darmiel commented on frontend/components/flashcard/Flashcard.tsx
> +						</Button>
I think `id` should be unique(?)

2023-05-11 09:10 UTC, darmiel commented on frontend/components/input/Button.tsx
> +			)} ${getSize(size ?? "")} ${className ?? ""}`}
`getSize` already has a default value (even if size is `undefined`)

2023-05-11 09:10 UTC, darmiel commented on frontend/components/flashcard/Flashcard.tsx
> +						}}
```suggestion
						onClick={() => setTurned(true)}
```

2023-05-11 09:10 UTC, darmiel commented on frontend/components/navigation/Header.tsx
> +					}}
```suggestion
					onClick={() => router.push("/login")}
```

2023-05-11 09:16 UTC, darmiel commented on frontend/components/deck/Deck.tsx
> +				{deck ? deck.name : "Create deck"}
I would prefer [Title Case](https://titlecaseconverter.com) to emphasis this button

2023-05-11 09:27 UTC, Julian702 commented on frontend/components/deck/DeckOverview.tsx
> +				<Deck></Deck>
look at components/deck/Deck.tsx

2023-05-11 09:32 UTC, darmiel commented on frontend/components/deck/DeckOverview.tsx
> +				<Deck></Deck>
got it, but it might be a good idea to include `id="create"` or something like that. (why, see above)

2023-05-11 09:35 UTC, Julian702 commented on frontend/components/deck/DeckOverview.tsx
> +			id={id}
@4KevR aleready mentioned above

2023-05-11 09:55 UTC, Luca-Hackl requested changes
Indents make code unreadable

2023-05-11 12:06 UTC, Julian702 commented on frontend/components/deck/Deck.tsx
> +	id?: string;
The reason ist @TomRomeo. I have changed it anyway.

2023-05-11 12:07 UTC, Julian702 commented on frontend/pages/login.tsx
> +		let name = document.querySelector("#name") as HTMLInputElement;
The reason is again @TomRomeo. I have changed it now.

2023-05-11 12:09 UTC, Julian702 commented on frontend/components/deck/Deck.tsx
> +				{deck ? deck.name : "Create deck"}
Agreed

2023-05-11 13:00 UTC, 4KevR approved these changes

2023-05-11 19:37 UTC, darmiel commented on frontend/components/deck/DeckOverview.tsx
> +					<Deck id="DeckId" key={i} deck={deck} />
Even though it's just mock data, the `<div id="">` should still be unique. May consider adding at least the index for unique ids.

```suggestion
					<Deck id=`DeckId_{i}` key={i} deck={deck} />
```

2023-05-11 19:37 UTC, darmiel commented on frontend/components/flashcard/Flashcard.tsx
> +						value={tempCard[+side].description}
explicitly converting to a number should not be necessary here.

2023-05-11 19:37 UTC, darmiel commented on frontend/components/flashcard/Flashcard.tsx
> +			)}
Some code can be deduplicated & made more readable: 


```suggestion
			<div className="flex flex-row items-center justify-between">
			
			{/* Show amount of cards left if on first side */}
			{!side && <div className="flex h-8 items-center text-sm font-semibold text-gray-400 sm:h-full">
				{cardsleft} cards left
			</div>}
			
			{/* Show arrow left if we're not on the first side */}
			{side && <ArrowLeft
				className="hidden h-8 hover:cursor-pointer sm:block md:h-10 lg:h-12"
				onClick={() => setSide(side - 1)}
			></ArrowLeft>}
			
			{/* Show arrow right if we're not on the last side */}
			{side <= tempCard.length - 1 && <ArrowRight
				className="hidden h-8 hover:cursor-pointer sm:block md:h-10 lg:h-12"
				onClick={() => setSide(side + 1)}
			></ArrowRight>}
			
			{/* Show rating buttons if we're on the last side */}
			{side >= tempCard.length -1 && <div className="flex w-full flex-row justify-between space-x-1 sm:justify-end">
				<Button id="buttonHardId" size="small" className="w-1/3 sm:w-auto">
					Hard
				</Button>
				<Button id="buttonMediumId" size="small" className="w-1/3 sm:w-auto">
					Medium
				</Button>
				<Button id="buttonEasyId" size="small" className="w-1/3 sm:w-auto">
					Easy
				</Button>
			</div>}
		</div>
```

> **Note** I'm not quite sure, when the rating buttons should come up,
but in this suggestion just assume you want to have it on the very last side.

2023-05-11 19:37 UTC, darmiel commented on frontend/pages/features.tsx
> +							description="Achievements and leaderboards make learning more engaging and motivating. Kioku helps you to achieve better results and stay on track with your personal learning goals! "
```suggestion
							description="Achievements and leaderboards make learning more engaging and motivating. Kioku helps you to achieve better results and stay on track with your personal learning goals!"
```

2023-05-11 19:37 UTC, darmiel commented on frontend/pages/home.tsx
> +							cloud native flashcard application that focusses on
```suggestion
							cloud native flashcard application that focuses on
```

2023-05-13 10:53 UTC, TomRomeo reviewed
Looks very good! I just found two small nits before we can merge this pr

2023-05-13 10:53 UTC, TomRomeo commented on frontend/pages/learn.tsx
> +			<div className="min-w-screen flex h-screen select-none flex-col bg-eggshell">
I think you forgot to wrap this page in the `authenticated` component.

2023-05-13 10:53 UTC, TomRomeo commented on frontend/components/flashcard/Flashcard.tsx
> +	 * How many cards a left on the stack
```suggestion
	 * How many cards are left on the stack
```

2023-05-13 15:27 UTC, TomRomeo approved these changes
♥

2023-05-13 15:31 UTC, merged