Fix error handling in frontend and backend
kioku-project/kioku pull request #265
Opened 2024-02-27 12:58 UTC by TomRomeo

## Description
This PR clarifies error messages in the backend and improves error display in the frontend with new toast library

## Resolved Issues
resolves #63

2024-02-28 08:17 UTC, Julian702 reviewed
Please fix the sonarcloud issues :)

2024-02-28 10:06 UTC, darmiel approved these changes
ta

2024-02-28 10:06 UTC, darmiel commented on backend/pkg/helper/security.go
> +	logger.Infof("Check password for valid format")
debug leftovers

2024-03-04 12:26 UTC, Julian702 requested changes
Great stuff, just some implementation details we should check

2024-03-04 12:26 UTC, Julian702 commented on frontend/components/input/NotificationButton.tsx
> +				</div>
```suggestion
				<div className="flex items-center space-x-2">
					<LoadingSpinner
						className="h-full"
						delay={0}
						theme="simple"
					/>
					<Trans>Loading...</Trans>
				</div>
```

2024-03-04 12:26 UTC, Julian702 commented on frontend/components/navigation/Navbar.tsx
> +							toast.success(t`Logged out`, { id: "logoutToast" });
We should agree on a consistent id format for all toasts.

2024-03-04 12:26 UTC, Julian702 commented on frontend/pages/login.tsx
> +		const toastID = toast.loading(t`Logging in...`, { id: "loginToast" });
s.a.

2024-03-04 12:26 UTC, Julian702 commented on frontend/util/api.ts
> +	}
Have seen this multiple times. Maybe refactor this to a util function?

2024-03-04 12:42 UTC, 4KevR reviewed
Looks great! Did not check in local build, I have some comments beforehand. Also, in some places, strange occurrences of commas appeared (see last comment), was this intended?

2024-03-04 12:42 UTC, 4KevR commented on backend/pkg/helper/errors.go
> +	return microErrors.Unauthorized(string(id), "You can not modify group admins")
Maybe `cannot`?

2024-03-04 12:42 UTC, 4KevR commented on backend/pkg/helper/errors.go
> +	return microErrors.Unauthorized(string(id), "You can not kick group admins")
s.a.

2024-03-04 12:42 UTC, 4KevR commented on backend/pkg/helper/errors.go
>  func NewFiberBadRequestErr(detail string) error {
missing newline

2024-03-04 12:42 UTC, 4KevR commented on backend/services/collaboration/handler/collaboration.go
> -	}
Why was this check removed? Should it be possible that a user kicks itself? I thought we have the `LeaveGroup` method for that.

2024-03-04 12:42 UTC, 4KevR commented on backend/services/user/handler/user.go
> +	logger.Infof("Received User.Register request")
Is this a conflicting change in regard to #240?

2024-03-04 12:42 UTC, 4KevR commented on backend/services/user/handler/user.go
> +	logger.Infof("Received User.Login request")
s.a.

2024-03-04 12:42 UTC, 4KevR commented on frontend/pages/login.tsx
> +					msg`Register today and start using the free flashcard application together with your friends. Simply create new decks or import existing decks from Anki and collaborate in groups.`,
see general comment

2024-03-04 13:52 UTC, TomRomeo commented on backend/services/user/handler/user.go
> +	logger.Infof("Received User.Register request")
It is a similar change, however that should not lead to problems down the line. :)

2024-03-04 13:52 UTC, TomRomeo commented on backend/services/user/handler/user.go
> +	logger.Infof("Received User.Login request")
as explained above

2024-03-06 14:29 UTC, Julian702 requested changes

2024-03-06 14:29 UTC, Julian702 commented on frontend/components/input/NotificationButton.tsx
> +				toast.error(err.message, { id: "notification-error" });
Use standardized format

2024-03-06 14:29 UTC, Julian702 commented on frontend/components/navigation/Navbar.tsx
> +							});
Is there a reason not to use the new `handleWithToast` function?

2024-03-06 14:29 UTC, Julian702 commented on frontend/pages/login.tsx
>  		}
Here as well

2024-03-06 14:29 UTC, Julian702 commented on frontend/pages/login.tsx
>  		}
And here again

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response.ok) mutateAll(groupMemberRoutes(groupID));
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response.ok)
		mutateAll([
			invitationsUserRoute,
			groupsRoute,
			groupRoute(groupID),
			...groupMemberRoutes(groupID),
		]);
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response?.ok) mutate(userRoute);
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response.ok) mutate(groupsRoute);
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response.ok) mutate(route);
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response.ok) mutate(groupMembersRoute(groupID));
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response.ok) mutate(groupsRoute);
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response.ok) mutate(groupsRoute);
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response.ok) mutate(route);
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response.ok) mutate(route);
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response.ok) mutate(decksRoute(groupID));
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response.ok) mutateAll([decksRoute(groupID), favoriteDecksRoute, activeDecksRoute]);
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response.ok) mutateAll([cardsRoute(deckID), ...cardRoutes(deckID)]);
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response.ok && card.deckID) mutate(cardsRoute(card.deckID));
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response.ok) mutateAll(cardRoutes(deckID));
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response.ok) mutateAll([cardsRoute(deckID), ...cardRoutes(deckID)]);
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/toasts.ts
> +	const res = await promise;
Could you rename this variable to match the standard?
```suggestion
	const response = await promise;
```

2024-03-06 14:29 UTC, Julian702 commented on frontend/util/api.ts
> +		"deleteUserToastID",
Is there a reason to sometimes using a toastID and sometimes not? I would suggest to set a custom id everywhere.

2024-03-13 08:26 UTC, Julian702 requested changes

2024-03-13 08:26 UTC, Julian702 commented on frontend/util/api.ts
> +	}
```suggestion
	if (response.ok) mutate(groupMembersRoute(groupID));
```

2024-03-13 18:47 UTC, 4KevR requested changes
Just tested locally, the new toast looks awesome! Found two issues.

2024-03-13 18:47 UTC, 4KevR commented on backend/services/frontend/handler/frontend.go
> -	}
As you removed the errors here, I think we can also remove them in the `errors.go` file

2024-03-13 18:47 UTC, 4KevR commented on backend/services/frontend/handler/frontend.go
> +		return helper.NewFiberReauthenticateError()
I just saw that the error thrown here leads to a 500 error in the response. This is due to the fact that in `main.go` of the frontend proxy, the fiber config only parses for micro errors and therefore (so my assumption) does not parse this 401 correctly. Do we want to address the issue in this PR or open a new issue for the error parsing?

2024-03-15 12:23 UTC, TomRomeo commented on backend/services/frontend/handler/frontend.go
> -	}
Good catch, I have removed the unused errors from the `errors.go` file.

2024-03-15 12:24 UTC, TomRomeo commented on backend/services/frontend/handler/frontend.go
> +		return helper.NewFiberReauthenticateError()
You are right. I have added the feature to the error handler to also handle fiber errors. They should now also be handled correctly. Thank you for finding that! <3

2024-03-16 15:33 UTC, 4KevR approved these changes

2024-03-17 21:11 UTC, merged