Create Selection Field Component
kioku-project/kioku pull request #267
Opened 2024-03-04 17:57 UTC by leonie2003

# Description
Add Selection Field Component that accepts a list of options (icon, title, description) as input.

## Resolved Issues
Resolves #260

2024-03-04 19:02 UTC, Julian702 requested changes
Looks great already, here are my first comments on some details :)

2024-03-04 19:02 UTC, Julian702 commented on frontend/components/input/SelectionField.tsx
> +										{" "}
Is this necessary?

2024-03-05 12:14 UTC, Julian702 requested changes
I have some more comments on this. Moreover I think we should avoid fixed widths in the component and define the width by setting additional classnames in the parent.

2024-03-05 12:14 UTC, Julian702 commented on frontend/components/input/SelectionField.tsx
> +				onKeyDown={() => {}}
I think this is a change resulting from a sonarcloud issue. Im not sure about the requirement here, but I think `combobox` would be the proper choice for the role. So the result should be something like this:
```suggestion
				role="combobox"
				onKeyUp={clickOnEnter}
				tabIndex={0}
```
Note that you can use the util function `clickOnEnter` to dispatch a click event on pressing enter.

PS: You can do something similar for the option with role `option`.

2024-03-05 12:14 UTC, Julian702 commented on frontend/components/input/SelectionField.tsx
> +				className="flex	hover:cursor-pointer"
Hover state is not necessary here
```suggestion
				className="flex cursor-pointer"
```

2024-03-05 12:14 UTC, Julian702 commented on frontend/components/input/SelectionField.tsx
> +							onKeyDown={() => {}}
Use `option` here

2024-03-05 12:37 UTC, Julian702 commented
We also need a story for the new component.

2024-03-09 15:50 UTC, Julian702 approved these changes

2024-03-09 15:55 UTC, TomRomeo approved these changes

2024-03-09 16:00 UTC, merged