fixed sonarcloud issues
kioku-project/kioku pull request #28
Opened 2023-05-13 15:38 UTC by Julian702

2023-05-13 15:42 UTC, TomRomeo approved these changes

2023-05-13 15:45 UTC, 4KevR requested changes
Looks good, see comment

2023-05-13 15:45 UTC, 4KevR commented on frontend/pages/login.tsx
> +		let password = document.querySelector("#password") as HTMLInputElement;
Maybe you could also change this to `const` to ensure consistency with the registerLogic

2023-05-13 16:21 UTC, 4KevR approved these changes

2023-05-14 14:31 UTC, memeToasty approved these changes

2023-05-16 08:22 UTC, merged