added first statistic components
kioku-project/kioku pull request #29
Opened 2023-05-17 09:50 UTC by Julian702

2023-05-17 11:33 UTC, TomRomeo requested changes
I really like the design! I just found a few nits :)

2023-05-17 11:33 UTC, TomRomeo commented on frontend/components/statistics/Statistic.tsx
> +	 * Heeader
```suggestion
	 * Header
```

2023-05-17 11:33 UTC, TomRomeo commented on frontend/components/statistics/Statistic.tsx
Maybe make the filename more expressive aswell

2023-05-17 11:33 UTC, TomRomeo commented on frontend/components/statistics/Statistic.stories.ts
> +		reference: "from 200",
maybe add the 'from' in the component directly, since it seems to be mentioned in all instances

2023-05-17 11:33 UTC, TomRomeo commented on frontend/components/statistics/StatisticOverview.tsx
> +export const StatisticOverview = ({ className }: StatisticOverviewProps) => {
Could you maybe change the StatisticOverview component to display it's childs next to each other instead of predefined statistics?

2023-05-17 14:24 UTC, Julian702 commented on frontend/components/statistics/Statistic.tsx
> + * UI component for basic statistics
I would rather stick to the short descriptions, as with all other components. In combination with the picture and the input parameters, this should be enough.

2023-05-17 14:24 UTC, Julian702 commented on frontend/components/statistics/Statistic.tsx
Feel free to suggest a better one :)

2023-05-17 15:16 UTC, memeToasty approved these changes

2023-05-17 15:16 UTC, memeToasty commented on frontend/components/input/Button.tsx
> +			"bg-kiokuDarkBlue border-kiokuDarkBlue text-eggshell shadow-sm",
Is that newline generated by the auto-formatter?

2023-05-17 15:16 UTC, memeToasty commented on frontend/components/statistics/Statistic.tsx
What about `ArrowedStatistic`?

2023-05-19 07:13 UTC, TomRomeo commented on frontend/components/statistics/Statistic.tsx
> + * UI component for basic statistics
Maybe we can have some input from @memeToasty and @4KevR, in my opinion the description and the file name really don't explain anything without storybook. IMO making both a little bit more descriptive really doesn't hurt.

2023-05-19 07:22 UTC, TomRomeo commented on frontend/components/statistics/Statistic.stories.ts
> +		reference: "from 200",
Then maybe extract the text into a separate property

2023-05-19 08:28 UTC, memeToasty commented on frontend/components/statistics/Statistic.tsx
> + * UI component for basic statistics
I think I agree with @TomRomeo. It does not really hurt to be descriptive. Even if it would be described elsewhere, it does not create confusion, but rather more clarification

2023-05-23 07:45 UTC, TomRomeo approved these changes

2023-05-23 07:54 UTC, merged