Feature/cardsides
kioku-project/kioku pull request #36
Opened 2023-06-02 21:40 UTC by 4KevR

This PR implements:
- card side concept (every card can have unlimited sides)
- added api endpoints for create, update and delete operations on card sides 
- updated postman collection
- changed error default code to 500 when the returned error is not from type `go-micro.dev/v4/errors`

Points up for discussion **before** this PR is merged:
1. How shall the card sides be accessed?
  - Current implementation: The existing endpoint `/api/decks/:deckID/cards`
  - Alternative: Manual request to a new endpoint `/api/cardSide/:cardSideID`, IDs will be given by `/api/decks/:deckID/cards`
2. Insert mechanism of new card sides
  - Current implementation: The request requires an `placeBeforeCardSideID` for the insert operation. When it is left blank, the new side will be inserted as the last side
3. General requirements of card sides
  - Current implementation: When a card is created, it should have at least one side. But the current state allows to delete all the sides. Up for discussion to add extra constraints.
  - Further thoughts: Also, it could be possible to implement a general *first* side and then an unlimited amount of extra sides. This side with a general *describing* function can be used to be displayed in an overview of the card in the overall list of cards in a deck. This question corresponds to point 1, as it could be possible to only return this *general* side in `/api/decks/:deckID/cards` and to add references for following requests to `/api/cardSide/:cardSideID`. The answer depends on the thoughts in the frontend implementation of the card side concept.

2023-06-07 13:08 UTC, Julian702 commented
@TomRomeo and I discussed your questions and here are our thoughts:

1. Endpoint `/api/decks/:deckID/cards` should return all cards with all sides like the following example. The sides of a card should have a  fixed order. A specific first side like mentioned in 3 isn't neccessary.
```JSON
{
   "cards": [
      {
         "cardID": "c-12345678"
         "sides": [
            {
               "header": "Front"
               "description": "Front"
            },
            {
               "header": "Back"
               "description": "Back"
            }
         ]
      }
   ]   
}
```

2. From our point of view it would be easier to send the whole card and let the backend either keep track of the changes or overwrite the whole card.

3. We think a card should always have at least one side. So to create a card, at least one side is required. At the moment the frontend doesn't allow to delete the last side of  a card. Nevertheless when the last side is deleted, the whole card should be deleted.

2023-06-09 11:29 UTC, TomRomeo requested changes

2023-06-09 11:29 UTC, TomRomeo commented on backend/services/carddeck/proto/carddeck.proto
> +	string description = 3;
Start from one
```suggestion
	string header = 1;
	string description = 2;
```

2023-06-09 11:29 UTC, TomRomeo commented on backend/services/frontend/main.go
> +	app.Delete("/api/cardSides/:cardSideID", svc.DeleteCardSideHandler)
What @Julian702 and I think would be better is that we do not expose the logic to modify or delete individual card sides as api requests, otherwise the frontend would have to keep track of all changes that happen to different card sides and send them once the editing of a card is confirmed. Instead, the card side mechanic should be 'hidden' from the frontend behind the create/modify/delete card logic and only happen internally between the services.

2023-06-09 14:36 UTC, 4KevR commented on backend/services/frontend/main.go
> +	app.Delete("/api/cardSides/:cardSideID", svc.DeleteCardSideHandler)
Okay, as this was already implemented before I asked for input on this PR, I thought we could leave the endpoints exposed but currently just don't use them in the frontend. Maybe we will later have a use case for them. Therefore the new endpoint for the modify card operation was introduced as part of your feedback, which deletes all the previous card sides and generates new ones.

2023-06-09 14:40 UTC, 4KevR commented on backend/services/carddeck/proto/carddeck.proto
> +	string description = 3;
Good catch, amended in 2c363f3232bd9f056fbbb50c380e05c7c5a6062d

2023-06-11 07:16 UTC, memeToasty approved these changes
👍

2023-06-11 07:26 UTC, TomRomeo approved these changes
♥

2023-06-11 07:37 UTC, Julian702 approved these changes

2023-06-11 07:39 UTC, merged