Adapting frontend to backend changes
kioku-project/kioku pull request #37
Opened 2023-06-05 11:07 UTC by Julian702

2023-06-11 13:41 UTC, TomRomeo requested changes
🌟

2023-06-11 13:41 UTC, TomRomeo commented on frontend/components/accessControl/Authenticated.tsx
> +			/>
If you put the toast container in [_app.tsx](https://github.com/kioku-project/kioku/blob/feat/frontend/frontend/pages/_app.tsx), you can remove the duplicate on the Login page and have it in a place that is more appropriate. 🙂

2023-06-11 13:41 UTC, TomRomeo commented on frontend/components/navigation/Navbar.tsx
>   * UI component for diplaying the Header
? 🙂
```suggestion
 * UI component for diplaying the Navbar
```

2023-06-11 13:41 UTC, TomRomeo commented on frontend/pages/features.stories.ts
Please move stories out of pages directory

2023-06-11 13:41 UTC, TomRomeo commented on frontend/pages/home.stories.ts
s.a.

2023-06-11 13:41 UTC, TomRomeo commented on frontend/pages/login.stories.ts
s.a.

2023-06-13 16:55 UTC, memeToasty approved these changes

2023-08-14 04:08 UTC, TomRomeo requested changes
Some minor changes. Additionally, the chromatic build does not seem to work anymore, please check out why.

2023-08-16 15:58 UTC, Julian702 commented on frontend/components/flashcard/Flashcard.tsx
> +	dueCards,
see no problem here

2023-08-16 17:03 UTC, Julian702 commented on frontend/components/Text.tsx
> +}
as discussed changed type of argument style in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:14 UTC, Julian702 commented on frontend/components/deck/DeckOverview.tsx
> +		group ? `/api/groups/${group?.groupID}/decks` : null,
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:14 UTC, Julian702 commented on frontend/components/deck/DeckOverview.tsx
> +						header={group?.groupName}
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:14 UTC, Julian702 commented on frontend/components/flashcard/Card.tsx
> +		<div className={`font-semibold text-kiokuDarkBlue ${className ?? ""}`}>
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:19 UTC, Julian702 commented on frontend/components/flashcard/Card.tsx
> +						></Edit2> */}
has to be reimplemented in the future

2023-08-16 17:19 UTC, Julian702 commented on frontend/components/flashcard/CardList.tsx
> +		<div id="cardListId" className={`flex flex-col ${className ?? ""}`}>
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:19 UTC, Julian702 commented on frontend/components/flashcard/Flashcard.tsx
> +	// }, [card, tempCard]);
removed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:19 UTC, Julian702 commented on frontend/components/flashcard/Flashcard.tsx
>  				className ?? ""
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:21 UTC, Julian702 commented on frontend/components/form/InputField.tsx
> +	return getStyle[style] ?? "";
as discussed changed type of attribute style in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:23 UTC, Julian702 commented on frontend/components/graphics/Badge.tsx
> +			)} ${className ?? ""}`}
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:23 UTC, Julian702 commented on frontend/components/graphics/Badge.tsx
> +	return getStyle[style] ?? "";
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:24 UTC, Julian702 commented on frontend/components/group/Member.tsx
> +			className={`font-semibold text-kiokuDarkBlue ${className ?? ""}`}
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:24 UTC, Julian702 commented on frontend/components/group/Member.tsx
> +	 *  User to display. If userID is undefined, placeholder for inviting users will be displayed.
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:24 UTC, Julian702 commented on frontend/components/group/Member.tsx
> +						{user?.userName}
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:25 UTC, Julian702 commented on frontend/components/group/Member.tsx
> +									)} */}
this code is waiting for backend change described in #58

2023-08-16 17:57 UTC, Julian702 commented on frontend/components/group/Member.tsx
> +			toast.info("User invited", {
since this in not only a problem here, I opened #63 to fix this in a future PR

2023-08-16 17:58 UTC, Julian702 commented on frontend/components/group/MemberList.tsx
> +		<div id={group.groupID} className={`flex flex-col ${className ?? ""}`}>
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:58 UTC, Julian702 commented on frontend/components/group/MemberList.tsx
> +	console.log(requestedUser);
removed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:58 UTC, Julian702 commented on frontend/components/input/Action.tsx
> +					className ?? ""
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:59 UTC, Julian702 commented on frontend/components/input/DangerAction.tsx
> +				className ?? ""
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:59 UTC, Julian702 commented on frontend/components/input/InputAction.tsx
> +				className ?? ""
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:59 UTC, Julian702 commented on frontend/components/layout/Header.tsx
> +				className ?? ""
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 17:59 UTC, Julian702 commented on frontend/components/layout/Section.tsx
> +	return getStyle[style] ?? getStyle.primary;
as discussed changed type of argument style in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:01 UTC, Julian702 commented on frontend/components/layout/Section.tsx
> + * UI component for displaying a section
Since this is a very general component used on multiple pages (settings, statistics, ...) as well as in other components, its not possible to give a more precise decription here

2023-08-16 18:02 UTC, Julian702 commented on frontend/components/layout/Section.tsx
> +interface ButtonProps {
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:02 UTC, Julian702 commented on frontend/components/navigation/Navbar.tsx
>  				className ?? ""
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:02 UTC, Julian702 commented on frontend/components/navigation/Tabs/CardsTab.tsx
> +		<div className={`flex flex-col md:flex-row ${className ?? ""}`}>
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:02 UTC, Julian702 commented on frontend/components/navigation/Tabs/DeckSettingsTab.tsx
> +		<div className="space-y-5">
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:03 UTC, Julian702 commented on frontend/components/navigation/Tabs/DecksTab.tsx
> +		<div className={`${className ?? ""}`}>
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:03 UTC, Julian702 commented on frontend/components/navigation/Tabs/GroupSettingTab.tsx
> +		<div className={`space-y-5 ${className ?? ""}`}>
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:03 UTC, Julian702 commented on frontend/components/navigation/Tabs/GroupsTab.tsx
> +		<div className="">
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:03 UTC, Julian702 commented on frontend/components/navigation/Tabs/InvitationsTabs.tsx
> +		<div>
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:04 UTC, Julian702 commented on frontend/components/navigation/Tabs/MembersTab.tsx
> +		<div className={`${className ?? ""}`}>
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:04 UTC, Julian702 commented on frontend/components/navigation/Tabs/StatisticsTab.tsx
> +		<div className="space-y-5">
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:12 UTC, Julian702 commented on frontend/components/navigation/Tabs/TabBar.tsx
> +			className={`flex flex-row justify-between ${className ?? ""}`}
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:14 UTC, Julian702 commented on frontend/components/navigation/Tabs/TabHeader.tsx
> +	return getIcon[style] ?? "";
as discussed changed type of argument style in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:16 UTC, Julian702 commented on frontend/components/navigation/Tabs/UserSettingsTab.tsx
> +		<div className="space-y-5">
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:44 UTC, Julian702 commented on frontend/components/navigation/Tabs/UserSettingsTab.tsx
> +	async function deleteGroup() {
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:44 UTC, Julian702 commented on frontend/pages/deck/[id]/index.tsx
> +								}[currentTab] || <div>Fehler</div>}
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:45 UTC, Julian702 commented on frontend/pages/group/[id]/index.tsx
> +							<div className="">
removed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:45 UTC, Julian702 commented on frontend/pages/group/[id]/index.tsx
> +							</div>
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:45 UTC, Julian702 commented on frontend/pages/index.tsx
> +							<div className="">
removed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:45 UTC, Julian702 commented on frontend/pages/index.tsx
> +												groups?.groups.filter(
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 18:45 UTC, Julian702 commented on frontend/pages/index.tsx
> +								}[currentTab] || <div>Fehler</div>}
fixed in f0c34fb0b8718edf1a104caf1d67e419060b7183

2023-08-16 19:17 UTC, Julian702 commented
Regarding the Chromatic Error: 
1. One Test is currently failing cause the Button for kicking members is deactivated and as stated above waiting for backend changes described in #58
2. The other errors are caused by frontend changes. Since some components are using API requests now instead of mocked data, the tests cant pass without login. I created #64 to fix this and expand tests to our new components.

2023-08-16 20:46 UTC, darmiel requested changes
I only finished half of the files - will look into it again after discussing/implementing some feedback to avoid duplicates

2023-08-16 20:46 UTC, darmiel commented on frontend/components/Text.tsx
> +	const getSize: { [size: string]: string } = {
maybe find a better name, e. g. `sizeMap`, `fontSizeMap`, `sizeToClass`, ...

2023-08-16 20:46 UTC, darmiel commented on frontend/components/Text.tsx
> +	return getSize[size] ?? getSize.medium;
you probably meant `md` since there is no `medium` key in the object.
```suggestion
	return getSize[size] ?? getSize.md;
```

2023-08-16 20:46 UTC, darmiel commented on frontend/components/deck/Deck.tsx
> +				{!!dueCards && dueCards > 0 && (
redundant check

```suggestion
				{dueCards > 0 && (
```

2023-08-16 20:46 UTC, darmiel commented on frontend/components/deck/Deck.tsx
> +							{dueCards < 100 ? dueCards : "99"}
```suggestion
							{Math.min(99, dueCards)}
```

2023-08-16 20:46 UTC, darmiel commented on frontend/components/deck/DeckOverview.tsx
> +								decks.decks.map(
```suggestion
							{decks?.decks.map(
```

2023-08-16 20:46 UTC, darmiel commented on frontend/components/flashcard/Card.tsx
> +											.catch((error) => {});
😊

2023-08-16 20:46 UTC, darmiel commented on frontend/components/flashcard/Flashcard.tsx
> +	const [side, setSide] = useState<number>(cardSide % card.sides?.length);
2 % undefined => `NaN`

```suggestion
	const [side, setSide] = useState<number>(cardSide % (card.sides?.length || 1));
```

2023-08-16 20:46 UTC, darmiel commented on frontend/components/flashcard/Flashcard.tsx
> +												)
this can cause unexpected behaviour. rather do this:

```suggestion
											setSide(oldSide => Math.min(
													oldSide,
													tempCard.sides.length - 2
											)
```

2023-08-16 20:46 UTC, darmiel commented on frontend/components/flashcard/Flashcard.tsx
> +											card.sides.splice(side, 1);
you're using a state which was altered just a few lines above.
example:

```ts
const [a, setA] = useState(0)
console.log(a) // 0
setA(1)
console.log(a) // 0
```

state changes are batched and processed async.

2023-08-16 20:46 UTC, darmiel commented on frontend/components/flashcard/Flashcard.tsx
> +							`${dueCards} card${dueCards != 1 ? "s" : ""} left`}
```suggestion
							`${dueCards} card${dueCards !== 1 ? "s" : ""} left`}
```

2023-08-16 20:46 UTC, darmiel commented on frontend/components/form/FormButton.tsx
> +	return getSize[size] ?? getSize.medium;
aha! here happened the `medium` copy-paste-error 🙂

2023-08-16 20:46 UTC, darmiel commented on frontend/components/form/InputField.tsx
> +					style!
I don't think `style` should be marked optional if we're a aggressively forcing it to be defined here

2023-08-16 20:46 UTC, darmiel commented on frontend/components/graphics/Badge.tsx
> +	return getStyle[style] ?? "";
s. a.

2023-08-17 17:30 UTC, 4KevR commented on frontend/components/graphics/Logo.tsx
> +				src="/kioku-logo.svg"
I am also unsure about this point, but there may be an option to unify the sources to make them easier for a configuration with a reverse proxy. The following would be possible:
```JavaScript
import kiokuLogo from "../../public/kioku-logo.svg"
...
<Image
	src={kiokuLogo}
	alt="Kioku"
	height={0}
	width={0}
	className="w-16 hover:cursor-pointer md:w-20 lg:w-24"
/>
```
Next.js will expose all the sources referenced in that way under `HOST/_next/...`. But I am unsure how this `_next` path behaves behind a reverse proxy.

2023-08-17 18:20 UTC, 4KevR requested changes
Looks good, I have a couple of comments for further review

2023-08-17 18:20 UTC, 4KevR commented on frontend/components/navigation/Tabs/GroupSettingTab.tsx
> +				></InputAction>
`groupDescription` may be undefined

2023-08-17 18:20 UTC, 4KevR commented on frontend/pages/deck/[id]/index.tsx
> +											deckID={deck?.deckID}
It was already checked if deck is defined

2023-08-17 19:01 UTC, darmiel commented on frontend/components/layout/Header.tsx
> +						{deck?.deckName}
`undefined` content is hidden

2023-08-17 19:02 UTC, darmiel commented on frontend/components/layout/Header.tsx
> +					{!deck && group && <div>{group.groupDescription}</div>}
same as above, `undefined` values are just not rendered so I would say intended behaviour

2023-08-18 03:14 UTC, TomRomeo commented on frontend/components/deck/Deck.tsx
> +							.catch((error) => {});
I think this was mainly done to please SonarCloud 😂

2023-08-20 11:57 UTC, Julian702 commented on frontend/components/Text.tsx
> +	size?: "xs" | "sm" | "md" | "lg" | "xl";
added type `Size` in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 11:57 UTC, Julian702 commented on frontend/components/Text.tsx
> +function getStyle(style: "primary" | "secondary"): string {
added type `Style` in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 11:58 UTC, Julian702 commented on frontend/components/Text.tsx
> +function getSize(size: "xs" | "sm" | "md" | "lg" | "xl"): string {
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 11:58 UTC, Julian702 commented on frontend/components/Text.tsx
> +	return getSize[size] ?? getSize.medium;
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:02 UTC, Julian702 commented on frontend/components/deck/Deck.tsx
> +	);
Maybe you could create a new issue describing why we should do that cause I think it's not that urgent to fix it in this pr.

2023-08-20 12:02 UTC, Julian702 commented on frontend/components/deck/Deck.tsx
> +			id={deck ? deck.deckID : "createDeckId"}
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:06 UTC, Julian702 commented on frontend/components/deck/Deck.tsx
> +							.catch((error) => {});
Yeah, I also think we schould make use of the callbacks, but maybe lets create an issue to deal with it later.

2023-08-20 12:06 UTC, Julian702 commented on frontend/components/deck/Deck.tsx
> +				{!!dueCards && dueCards > 0 && (
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:07 UTC, Julian702 commented on frontend/components/deck/Deck.tsx
> +							{dueCards < 100 ? dueCards : "99"}
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:07 UTC, Julian702 commented on frontend/components/deck/Deck.tsx
> +										.catch((error) => {});
s.a.

2023-08-20 12:10 UTC, Julian702 commented on frontend/components/deck/Deck.tsx
> +		) as HTMLInputElement;
Lets discuss this in our next Weekly.

2023-08-20 12:10 UTC, Julian702 commented on frontend/components/deck/DeckOverview.tsx
> +			id={group?.groupID}
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:10 UTC, Julian702 commented on frontend/components/deck/DeckOverview.tsx
> +								decks.decks.map(
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:10 UTC, Julian702 commented on frontend/components/deck/DeckOverview.tsx
> +			id={group?.groupID}
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:10 UTC, Julian702 commented on frontend/components/deck/DeckOverview.tsx
> +								decks.decks.map(
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:11 UTC, Julian702 commented on frontend/components/deck/DeckOverview.tsx
> +								decks.decks.map(
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:12 UTC, Julian702 commented on frontend/components/deck/DeckOverview.tsx
> +									.catch((error) => {});
s.a.

2023-08-20 12:12 UTC, Julian702 commented on frontend/components/deck/DeckOverview.tsx
> +								decks.decks.map(
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:12 UTC, Julian702 commented on frontend/components/deck/DeckOverview.tsx
> +								decks.decks.map(
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:16 UTC, Julian702 commented on frontend/components/deck/DeckOverview.tsx
> +	const { data: decks } = useSWR(
I think it's not that easy because of our backend response (decks.decks). For the moment I changed the data type in the map function to avoid the code above.

2023-08-20 12:24 UTC, Julian702 commented on frontend/components/flashcard/Card.tsx
> +						onClick={() => {
Second "even better" example isn't working.

2023-08-20 12:24 UTC, Julian702 commented on frontend/components/flashcard/Card.tsx
> +											.catch((error) => {});
s.a.

2023-08-20 12:24 UTC, Julian702 commented on frontend/components/flashcard/Card.tsx
> +									.catch((error) => {});
s.a.

2023-08-20 12:24 UTC, Julian702 commented on frontend/components/flashcard/CardList.tsx
> +					cards.cards.map((card: CardType) => (
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:25 UTC, Julian702 commented on frontend/components/flashcard/Flashcard.tsx
> +	const [side, setSide] = useState<number>(cardSide % card.sides?.length);
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:25 UTC, Julian702 commented on frontend/components/flashcard/Flashcard.tsx
> +												)
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:28 UTC, darmiel commented on frontend/components/flashcard/Card.tsx
> +						onClick={() => {
my bad, should've been `setCard?.()`

2023-08-20 12:31 UTC, Julian702 commented on frontend/components/flashcard/Flashcard.tsx
> +											card.sides.splice(side, 1);
I haven't noticed any unexpected behaviour here. What's your solution to avoid using a state altered before?

2023-08-20 12:31 UTC, Julian702 commented on frontend/components/flashcard/Flashcard.tsx
> +							`${dueCards} card${dueCards != 1 ? "s" : ""} left`}
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:31 UTC, Julian702 commented on frontend/components/flashcard/Flashcard.tsx
> +							}}
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:33 UTC, Julian702 commented on frontend/components/form/InputField.tsx
> +	style?: "primary" | "secondary" | "tertiary";
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:34 UTC, Julian702 commented on frontend/components/form/InputField.tsx
> +	};
What exactly do you mean?

2023-08-20 12:34 UTC, Julian702 commented on frontend/components/form/InputField.tsx
> +	};
What exactly do you mean?

2023-08-20 12:34 UTC, Julian702 commented on frontend/components/form/InputField.tsx
> +					style!
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:34 UTC, Julian702 commented on frontend/components/graphics/Badge.tsx
> +	style?: "primary" | "secondary" | "tertiary";
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:39 UTC, Julian702 commented on frontend/components/graphics/Logo.tsx
> +				src="/kioku-logo.svg"
This change was caused by the component working on one page but not on another. I added an import here as @4KevR  suggested.

2023-08-20 12:39 UTC, Julian702 commented on frontend/components/group/Member.tsx
> +														.catch((error) => {});
s.a.

2023-08-20 12:39 UTC, Julian702 commented on frontend/components/group/Member.tsx
> +												.catch((error) => {});
s.a.

2023-08-20 12:39 UTC, Julian702 commented on frontend/components/group/Member.tsx
> +														.catch((error) => {});
s.a.

2023-08-20 12:39 UTC, Julian702 commented on frontend/components/group/Member.tsx
> +												.catch((error) => {});
s.a.

2023-08-20 12:39 UTC, Julian702 commented on frontend/components/group/Member.tsx
> +												.catch((error) => {});
s.a.

2023-08-20 12:41 UTC, Julian702 commented on frontend/components/input/DangerAction.tsx
> +	description?: string;
This behaviour is intended. I added some stories in 7b69932b913ca6cf11db44fd1071d49e1ef06ade to visualise how the component looks in different variations.

2023-08-20 12:41 UTC, Julian702 commented on frontend/components/input/InputAction.tsx
> +	value?: string;
same as above

2023-08-20 12:42 UTC, Julian702 commented on frontend/components/layout/Header.tsx
> +					)}
There's not always an intention :D

2023-08-20 12:42 UTC, Julian702 commented on frontend/components/navigation/Navbar.tsx
> + * UI component for diplaying the NavBar
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:42 UTC, Julian702 commented on frontend/components/navigation/Tabs/CardsTab.tsx
> +		card?.cardID == newCard.cardID ? setCard(undefined) : setCard(newCard);
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:43 UTC, Julian702 commented on frontend/components/navigation/Tabs/GroupSettingTab.tsx
> +				></InputAction>
Should be no problem as stated above.

2023-08-20 12:43 UTC, Julian702 commented on frontend/pages/deck/[id]/index.tsx
> +											deckID={deck?.deckID}
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:44 UTC, Julian702 commented on frontend/pages/deck/[id]/index.tsx
> +											groupID={deck?.groupID}
fixed in 7b69932b913ca6cf11db44fd1071d49e1ef06ade

2023-08-20 12:45 UTC, Julian702 commented on frontend/components/deck/DeckOverview.tsx
> +								decks.decks.map(
sponsored by WIFIonICE :D

2023-08-20 12:49 UTC, Julian702 commented on frontend/components/flashcard/Card.tsx
> +						onClick={() => {
I thoughed I also tried this, but now it's working.

2023-08-20 18:51 UTC, darmiel commented on frontend/components/deck/DeckOverview.tsx
> +	const { data: decks } = useSWR(
what about this then?

```suggestion
	const { data: decks } = useSWR<{ deck: Deck }>(
```

2023-08-20 18:54 UTC, darmiel commented on frontend/components/form/InputField.tsx
> +	};
instead of this:

```ts
function abc() {
  const styles = { ... }
}
```

this:

```ts
const styles = { ... }
function abc() {
}
```

2023-08-20 19:24 UTC, Julian702 commented on frontend/components/form/InputField.tsx
> +	};
But why?

2023-08-20 19:39 UTC, 4KevR approved these changes
Done from my side of requested changes👍

2023-08-20 20:02 UTC, darmiel requested changes

2023-08-20 20:02 UTC, darmiel commented on frontend/pages/index.tsx
> +								}[currentTab] || <div>Error</div>}
```suggestion
								}[currentTab] ?? <div>Error</div>}
```

2023-08-20 20:02 UTC, darmiel commented on frontend/types/User.ts
> +	groupRole?: "ADMIN" | "WRITE" | "READ" | "INVITED" | "REQUESTED";
plz extract to own type 😊

2023-08-21 07:38 UTC, darmiel commented on frontend/components/deck/DeckOverview.tsx
> +	const { data: decks } = useSWR(
I just noticed that your partial-deck type does not match the `Deck` type (`due` => `dueCards`) was this done on purpose? If yes, I think the naming of the response should be changed to `dueCards` to match the `Deck` type.

Either way, since `deck` is only a partial `Deck`, we can use one of the following types inside `{ deck: ... }`:

```ts
Pick<Deck, 'deckID' | 'deckName' | 'dueCards'>;
Pick<Deck, 'deckID' | 'deckName'> & { due: number };
Omit<Deck, 'createdAt' | 'groupID' >
```

2023-08-22 10:21 UTC, Julian702 commented on frontend/components/Text.tsx
> +	const getSize: { [size: string]: string } = {
fixed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0 with changes discussed below

2023-08-22 10:22 UTC, Julian702 commented on frontend/components/form/InputField.tsx
> +	};
fixed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0 as discussed below

2023-08-22 10:27 UTC, Julian702 commented on frontend/components/Text.tsx
> +}
changed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0

2023-08-22 10:28 UTC, Julian702 commented on frontend/components/input/Button.tsx
> +	style?: Style | "error" | "warning";
not necessary due to changes above

2023-08-22 10:28 UTC, Julian702 commented on frontend/components/layout/Header.tsx
> +				(group.groupRole == "INVITED" || !group?.groupRole) && (
fixed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0

2023-08-22 10:28 UTC, Julian702 commented on frontend/components/layout/Header.tsx
> +			{!deck && group && group.groupRole == "REQUESTED" && (
fixed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0

2023-08-22 10:29 UTC, Julian702 commented on frontend/components/layout/Section.tsx
> +	return getStyle[style] ?? getStyle.primary;
changed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0 as discussed above

2023-08-22 10:31 UTC, Julian702 commented on frontend/components/navigation/Tabs/DeckSettingsTab.tsx
> +	const [isDelete, setDelete] = useState(false);
renamed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0

2023-08-22 10:31 UTC, Julian702 commented on frontend/components/navigation/Tabs/GroupSettingTab.tsx
> +								group.groupType == "PRIVATE"
fixed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0

2023-08-22 10:31 UTC, Julian702 commented on frontend/components/navigation/Tabs/GroupSettingTab.tsx
> +	const [isDelete, setDelete] = useState(false);
renamed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0

2023-08-22 10:32 UTC, Julian702 commented on frontend/components/navigation/Tabs/GroupsTab.tsx
> +			<DeckOverview></DeckOverview>
fixed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0

2023-08-22 10:32 UTC, Julian702 commented on frontend/components/navigation/Tabs/InvitationsTabs.tsx
> +				></DeckOverview>
fixed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0

2023-08-22 10:32 UTC, Julian702 commented on frontend/components/navigation/Tabs/TabBar.tsx
> +							currentTab == tab
fixed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0

2023-08-22 10:34 UTC, Julian702 commented on frontend/components/navigation/Tabs/TabHeader.tsx
> +		| "user";
replaced with `keyof typeof` in 52c582c32858c6912b3a5fa1b1062bfea2815ad0 so extracting into type isn't necessary

2023-08-22 10:34 UTC, Julian702 commented on frontend/components/navigation/Tabs/UserSettingsTab.tsx
> +	const [isDelete, setDelete] = useState(false);
renamed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0

2023-08-22 10:34 UTC, Julian702 commented on frontend/pages/deck/[id]/index.tsx
> +								}[currentTab] || <div>Error</div>}
fixed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0

2023-08-22 10:34 UTC, Julian702 commented on frontend/pages/group/[id]/index.tsx
> +	const [currentTab, setTab] = useState("decks");
renamed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0

2023-08-22 10:35 UTC, Julian702 commented on frontend/pages/group/[id]/index.tsx
> +								}[currentTab] || <div>Error</div>}
fixed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0

2023-08-22 10:35 UTC, Julian702 commented on frontend/pages/index.tsx
> +	const [currentTab, setTab] = useState("decks");
renamed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0

2023-08-22 10:36 UTC, Julian702 commented on frontend/pages/index.tsx
> +								}[currentTab] || <div>Error</div>}
fixed in 52c582c32858c6912b3a5fa1b1062bfea2815ad0

2023-08-22 10:39 UTC, Julian702 commented on frontend/types/User.ts
> +	groupRole?: "ADMIN" | "WRITE" | "READ" | "INVITED" | "REQUESTED";
extracted enum groupRole from `types/Group.ts`  and replaced with `keyof typeof` in 52c582c32858c6912b3a5fa1b1062bfea2815ad0 so extracting into type isn't necessary

2023-08-22 12:17 UTC, Julian702 commented on frontend/components/deck/Deck.tsx
> +							.catch((error) => {});
created #66

2023-08-24 04:59 UTC, TomRomeo commented on frontend/components/flashcard/Card.tsx
> +	}
I was prototyping this for a little bit and this was something I came up with:
```typescript
async function createGeneric<Entity>(input: HTMLInputElement, entity: Entity) {
    if (!input.value) {
        input.focus();
        return;
    }
    if (entity instanceof Card) {
        let response = await authedFetch(`/api/decks/${card.deckID}/cards`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(body),
        });
        if (response?.ok) {
            input.value = "";
            toast.info("Card created!", { toastId: "newCardToast" });
            mutate(`/api/decks/${card.deckID}/cards`);
            mutate(`/api/decks/${card.deckID}/pull`);
            mutate(`/api/decks/${card.deckID}/dueCards`);
        } else {
            toast.error("Error!", { toastId: "newCardToast" });
        }
    }
    else if () {
        // ...
    }
}
```

But after some consideration, I don't think this is really necessary or helpful in this context, since it really only moves the to another place. Therefore, I will resolve this.

2023-08-24 05:02 UTC, TomRomeo commented on frontend/components/layout/Section.tsx
> + * UI component for displaying a section
As discussed in our weekly, maybe change this to something such as:
"UI component to group elements with an optional title and kioku theming"

2023-08-24 05:03 UTC, TomRomeo approved these changes
Please think about rewording the description of the Section component again. Other than that, I am happy with this PR! :)

2023-08-26 12:49 UTC, Julian702 commented on frontend/components/deck/Deck.tsx
> +		) as HTMLInputElement;
fixed in 67b2b67eb8ad5933ed2e55ad9f0171a273154725

2023-08-27 14:24 UTC, Julian702 commented on frontend/components/deck/DeckOverview.tsx
> +	const { data: decks } = useSWR(
fixed in f3305fb4149544dc5e2b988a8e08d772d3211b20

2023-08-28 15:55 UTC, merged