Build images on push on main
kioku-project/kioku pull request #4
Opened 2022-11-23 08:11 UTC by memeToasty

I am actually not sure if this workflow works, but it should according to [this article](https://github.com/marketplace/actions/build-and-push-docker-images)

2022-11-28 20:12 UTC, TomRomeo approved these changes
looks like it might work 👍🏼

2022-11-28 20:31 UTC, statzie commented
I think you're still missing the login action - for ghcr, something like:

```yaml
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
```

2022-11-29 16:46 UTC, memeToasty commented
According to the article, it says "_Building from the current repository automatically uses the [GitHub Token](https://docs.github.com/en/actions/security-guides/automatic-token-authentication), so it does not need to be passed._"

2022-11-29 16:52 UTC, statzie commented
> According to the article, it says "_Building from the current repository automatically uses the [GitHub Token](https://docs.github.com/en/actions/security-guides/automatic-token-authentication), so it does not need to be passed._"

Yep, looks like you're right 😄
https://github.com/docker/build-push-action/blob/175d02bffea74695e96b351069ac938b338802f9/action.yml#L94

2022-11-30 14:07 UTC, TomRomeo approved these changes
👍🏼⚡

2022-11-30 14:08 UTC, 4KevR requested changes
See note

2022-11-30 14:08 UTC, 4KevR commented on .github/workflows/ci.yml
> +          tags: ghcr.io/friesenjungs/${{ env.FRONTEND_SERVICE_IMAGE_NAME }}:latest
I think you should change the label to include "ghcr.io/kioku-project"

2022-11-30 14:11 UTC, memeToasty commented on .github/workflows/ci.yml
> +          tags: ghcr.io/friesenjungs/${{ env.FRONTEND_SERVICE_IMAGE_NAME }}:latest
obviously, yeah.
Sorry, major oversight

2022-11-30 14:13 UTC, memeToasty commented on .github/workflows/ci.yml
> +          tags: ghcr.io/friesenjungs/${{ env.FRONTEND_SERVICE_IMAGE_NAME }}:latest
Should be resolved now

2022-11-30 14:14 UTC, 4KevR approved these changes
👍

2022-11-30 14:19 UTC, statzie commented on .github/workflows/ci.yml
> +          file: ./frontend/Dockerfile
Did you test this?
I think it should be:
```suggestion
          context: ./frontend
          file: Dockerfile
```
Otherwise the instruction of the Dockerfile would be (metaphorically)
```dockerfile
COPY go.mod go.sum ./
```
instead of
```dockerfile
COPY ./frontend/go.mod ./frontend/go.sum ./
```

2022-11-30 14:19 UTC, statzie commented on .github/workflows/ci.yml
> +          file: ./backend/cmd/service/login/Dockerfile
s. a.

```suggestion
          context: ./backend/cmd/service/login
          file: Dockerfile
```

2022-11-30 14:19 UTC, statzie commented on .github/workflows/ci.yml
> +          file: ./backend/cmd/service/register/Dockerfile
s. a.

```suggestion
          context: ./backend/cmd/service/register
          file: Dockerfile
```

2022-11-30 14:36 UTC, memeToasty commented on .github/workflows/ci.yml
> +          file: ./frontend/Dockerfile
I think you are right.
But no, I have not tested this before

2022-11-30 15:26 UTC, Julian702 approved these changes

2022-11-30 15:27 UTC, merged