added srs service
kioku-project/kioku pull request #42
Opened 2023-06-11 19:35 UTC by TomRomeo

This PR implements the backend logic of the srs service.

2023-06-11 19:48 UTC, memeToasty requested changes
I really like how our core of our applications comes together, just some minor oversights <3

xoxo Cloud-boy

2023-06-11 19:48 UTC, memeToasty commented on backend/services/srs/resources/clusterrole.yaml
These Kubernetes files are not being used by our deployment, so they can be removed.
The service needs to be added like the user-service like [here](https://github.com/kioku-project/kioku/blob/main/helm/kioku/templates/user.yaml). I can do that for you in this branch if you want.

In addition to that, there needs to be additional build-scripts for Github actions, so the images will automatically be built. I also can do that

2023-06-11 19:48 UTC, memeToasty commented on backend/services/srs/resources/configmap.yaml
see above

2023-06-11 19:48 UTC, memeToasty commented on backend/services/srs/resources/deployment.yaml
see above

2023-06-11 19:48 UTC, memeToasty commented on backend/services/srs/resources/rolebinding.yaml
see above

2023-06-11 20:16 UTC, memeToasty requested changes
copy paste error

2023-06-11 20:16 UTC, memeToasty commented on .github/workflows/srs_service.yml
> +name: Carddeck Service
```suggestion
name: SRS Service
```

2023-06-11 20:37 UTC, 4KevR requested changes
Looks very good, I have a couple of nits for further improvement.

2023-06-11 20:37 UTC, 4KevR commented on backend/pkg/model/userCardBinding.go
> +	CardID  string
Do you want to create a combined primary key? And/or it is useful to set a `not null`

2023-06-11 20:37 UTC, 4KevR commented on backend/pkg/model/userCardBinding.go
> +		id := helper.GenerateID('S')
`S` is already used by CardSide

2023-06-11 20:37 UTC, 4KevR commented on backend/pkg/model/userCardBinding.go
> +	LastIvl uint32 `gorm:"not null"`
I think I would prefer to write `LastInterval` for better readability

2023-06-11 20:37 UTC, 4KevR commented on backend/services/frontend/handler/frontend.go
> +	rating, err := strconv.ParseInt(data["rating"], 10, 0)
Maybe it could be possible to introduce a custom request serializer for this request as already existing for e.g. `FiberCreateCardRequestBody`. Then it could be possible to give the rating as an actual integer in the request which would make it more intuitive I think. But can be discussed.

2023-06-11 20:37 UTC, 4KevR commented on backend/services/srs/handler/srs.go
> +		cardBinding.LastIvl = uint32(newIvl)
as above, maybe better `newInterval`

2023-06-11 20:37 UTC, 4KevR commented on backend/services/srs/handler/srs.go
> +	}
Maybe you could use the `converter.ConvertToTypeArray`. For this, you have to create a new type converter in `typeConverter.go`

2023-06-11 20:37 UTC, 4KevR commented on backend/store/postgres.go
> +}
```suggestion
func (s *SrsStoreImpl) ModifyUserCard(userCard *model.UserCardBinding) error {
	return s.db.Save(&model.UserCardBinding{
		ID:      userCard.ID,
		UserID:  userCard.UserID,
		CardID:  userCard.CardID,
		DeckID:  userCard.DeckID,
		Type:    userCard.Type,
		Due:     userCard.Due,
		LastIvl: userCard.LastIvl,
		Factor:  userCard.Factor,
	}).Error
}
```
Maybe just return the error

2023-06-11 20:37 UTC, 4KevR commented on backend/services/srs/handler/srs.go
> +	cardBinding, err := e.store.GetCardBinding(req.UserID, req.CardID)
The request is not using the `c.Params("deckID")` which could be used as an additional parameter in the higher level request in the frontend proxy. It could be used to further contain the use of this method call, so that an api call to the push cannot be done for a card which is not in the current `deckID` context.

2023-06-12 07:50 UTC, TomRomeo commented on backend/pkg/model/userCardBinding.go
> +	CardID  string
implemented in 75f4f57

2023-06-12 07:51 UTC, TomRomeo commented on backend/pkg/model/userCardBinding.go
> +		id := helper.GenerateID('S')
changed to "B" in 75f4f57

2023-06-12 07:51 UTC, TomRomeo commented on backend/pkg/model/userCardBinding.go
> +	LastIvl uint32 `gorm:"not null"`
done with 75f4f57

2023-06-12 07:51 UTC, TomRomeo commented on backend/services/frontend/handler/frontend.go
> +	rating, err := strconv.ParseInt(data["rating"], 10, 0)
done with 75f4f57

2023-06-12 07:51 UTC, TomRomeo commented on backend/services/srs/handler/srs.go
> +	}
done with 75f4f57

2023-06-12 07:51 UTC, TomRomeo commented on backend/store/postgres.go
> +}
👍🏼⚡ 75f4f57

2023-06-12 07:52 UTC, TomRomeo commented on backend/services/srs/handler/srs.go
> +	cardBinding, err := e.store.GetCardBinding(req.UserID, req.CardID)
good idea (implemented in 75f4f57)

2023-06-12 10:27 UTC, 4KevR approved these changes
Looks good, maybe we could do some naming adjustments

2023-06-12 10:27 UTC, 4KevR commented on backend/pkg/converter/typeConverter.go
> +func CardDeckCardSideToSrsProtoCardSideConverter(cardSide *pbCardDeck.CardSide) *pbSrs.Side {
s.a. `CardDeckProtoCardSideToSrsProtoCardSideConverter`

2023-06-12 10:27 UTC, 4KevR commented on backend/pkg/converter/typeConverter.go
> +func CardDeckCardToSrsProtoCardConverter(card *pbCardDeck.Card) *pbSrs.Card {
Naming, maybe adjust to `CardDeckProtoCardToSrsProtoCardConverter`

2023-06-12 10:49 UTC, memeToasty approved these changes

2023-06-12 12:19 UTC, Julian702 requested changes
Please reduce duplication

2023-06-12 13:10 UTC, merged