[Feature] account deletion
kioku-project/kioku pull request #68
Opened 2023-08-25 07:58 UTC by TomRomeo

This PR implements the requested feature of account deletion to comply with GDPR / DSGVO (#61)

The endpoint is `DELETE` `/api/user` 

With account deletion, the following data is also ereased:
- revlog entries
- user-card bindings
- user-group-role bindings

> **Important**
> With the current implementation, if a user is part of a group, the group does **not** get deleted. Therefore, home groups will remain and groups can end up without any admins.

How would you propose we solve that problem?
Should 'empty' groups be deleted? What about non-empty groups where no admin would remain?

closes #61

2023-08-25 08:05 UTC, darmiel requested changes
👑 (only formatting)

2023-08-25 08:05 UTC, darmiel commented on backend/pkg/model/cardside.go
> +        Card               Card `gorm:"constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`
what happened to the format?

2023-08-25 08:05 UTC, darmiel commented on backend/pkg/model/groupUserRole.go
> +        Group    Group `gorm:"constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`
go fmt plz

2023-08-25 08:05 UTC, darmiel commented on backend/pkg/model/revlog.go
> +        User   User `gorm:"constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`
🧐

2023-08-25 08:05 UTC, darmiel commented on backend/pkg/model/userCardBinding.go
> +        User        User    `gorm:"constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`
🤨

2023-08-25 08:05 UTC, darmiel commented on backend/services/user/handler/user.go
> +        }
😡

isn't your GoLand set to automatically format?

2023-08-25 08:06 UTC, TomRomeo commented on backend/services/user/handler/user.go
> +        }
wrote with nvim™

2023-08-25 08:08 UTC, memeToasty commented on backend/services/user/handler/user.go
> +        }
![aCtUaLlY](https://media.tenor.com/eRD89_uiAvsAAAAC/nerd-well-actually.gif)

2023-08-25 08:10 UTC, darmiel commented on backend/services/user/handler/user.go
> +        }
isn't your nvim set to automatically format?

2023-08-25 14:22 UTC, darmiel approved these changes

2023-08-25 14:57 UTC, Julian702 commented
From my point of view, we should also delete the Home Group including all decks to ensure that no user data is left.

With empty public groups, the question is whether an external user can learn decks from the group. As far as I remember we had agreed that you don't have to join a group to learn (reference and not copy) the public decks of the group. The empty group could be deleted, but not the decks in the group that are referenced by other users. However, since no one has the rights to edit these decks anymore, it would be a possibility to replace the references with copies. 
Private empty groups can be deleted in any case, since nobody has access to them.

In this context, let's discuss again and define what private and public means, to cover all cases. For example, can a public group also have private decks?
My suggestion would be to specify the attribute private and public only for decks, as the current solution is confusing and duplicated. Private decks can then be deleted and references to public decks can be replaced with copies as described above before deletion.
For groups we should then save whether you can join them. I could imagine the values "Anyone can join", "Request to join" or "Closed". In any case, an empty group would then be deleted.

We should also think about keeping non-user related data for a short time to be able to restore it if needed or if this is handled by our backup strategy in the future.

In the case that there is no admin left, from my point of view users would have to create a new group and copy decks, as I can't think of a reliable strategy to designate a new admin.

2023-08-28 16:27 UTC, Julian702 commented
> I don't think we should keep the user data as a backup, if the user decides to delete the account, it should be irreversible. Because a backup would lead to new problems.

As I described above, the backup was not about user-related data but about groups and decks, for example. I could imagine deleting the associations, but not the entries in the database itself, so that they could be restored.

> For the case of the deletion of an admin account of a group I would suggest to promote the user with the highest role to be the admin. It is an easier procedure for the moment as we don't have the "copy" feature yet.

What happens then if several users have the same role? Will one of them be promoted? Will everyone be promoted? I think both solutions are problematic, because users without write access could even delete the group for everyone after promotion. I think the simplest solution is not to promote anyone at first, so that no user can lose data that way. Afterwards, we can address the copy feature.

2023-08-29 06:27 UTC, TomRomeo commented
I started work on #56 as well, since this issue covers the same group logic.
The current approach would be:
1. User leaves group
2. if no user remain -> delete group
3. if user remain but no admin remains -> also delete group

I think this might be the most straight forward solution. A group admin can transfer ownership before leaving the group but just setting a random user to admin is not a good solution, I think.

As for handling of private / public decks / copies, I think we have to further specify this behavior in another meeting / issue / PR, because as Kevin mentioned, this is not implemented yet at all.

2023-08-29 09:18 UTC, Julian702 commented
> 2. if no user remain -> delete group

This is currently only possible with private groups until we can automatically replace references to public decks.

> 3. if user remain but no admin remains -> also delete group

This is not possible at all, since the members would lose their decks. In this case, the group must remain to give them the possibility to continue learning or to transfer the decks to their home group in the future.

> A group admin can transfer ownership before leaving the group but just setting a random user to admin is not a good solution, I think.

I agree, I think the best option would be to force the last admin to either delete the group or make another group member the admin before he is allowed to leave the group.

2023-08-30 03:54 UTC, TomRomeo commented
> This is currently only possible with private groups until we can automatically replace references to public decks.

> This is not possible at all, since the members would lose their decks. In this case, the group must remain to give them the possibility to continue learning or to transfer the decks to their home group in the future.

I think it is more sensible to implement it this way first (deleting groups as I described above) and later change the logic to account for referenced decks and team members, since this requires a lot of logic that is not implemented yet and at the current rate would lead to most groups not being deleted and dangling without any admins, which is quite ugly in my opinion.

2023-08-31 07:28 UTC, Julian702 commented
As we discussed in our last Weekly, here is a brief summary of the simple solution we have agreed on for now. 

When a user deletes their account, the following steps must be completed.

1. Delete all account information, including the user's home group and all group memberships.

2. Delete all private decks in empty groups (currently all decks in private groups, as we do not differentiate here).

3. Delete all groups without members and without decks.

This simple logic prevents that members of a group lose their decks, because the last admin deletes his account and the group is removed as well.

Regarding leaving a group described in #56, we agreed that we force the last admin to promote another group member or delete the group. This has to be implemented mostly in the frontend, as the backend only has to return an error here. I will create a new issue for the frontend implementation and link it here.

2023-09-06 14:56 UTC, Julian702 commented
I encountered a few problems during testing:

- When I try to delete my account I get the following response (500):
   ```no existing user with email```
- When I try to leave my non-empty group as non-admin or as last admin I get the following response (200):
   ```
   {
      success: true
   }
   ```
   However, I am still in the group and can repeat the request several times with the same answer. Besides, I think that the status code 200 should be sufficient and a body is not needed here.

2023-09-07 01:26 UTC, TomRomeo commented
You are right, I indeed missed this case in the leave group logic. I have now added it.
Of course, we would not have this problem if we would just simplify the group logic to deleting the group once the last admin leaves but oh well. 😭

I have also changed the returned response to align with already existing responses.

2023-09-07 10:33 UTC, Julian702 commented
Thanks for fixing the bug described above. Unfortunately I found another two problems during testing:

- response from DELETE /api/user still not matching our project default
- when deleting the last admin account in a private group, the group ist deleted although there are other members in this group

I have not tested all possible scenarios at this point. Please check the logic for deleting decks and groups after account deletion I described in #61. Could you also remove the code smell detected by SonarCloud?

2023-09-09 07:29 UTC, Julian702 commented
When I started adapting the frontend, I noticed that the two endpoints feel a bit inconsistent. 

DELETE `/api/user`
DELETE `/api/groups/G-LwvbfUvs/members/leave`

We should keep a consistent scheme here, considering the promotion and demotion endpoints to be implemented next. What's your opinion?

2023-09-20 07:59 UTC, memeToasty approved these changes

2023-10-02 07:23 UTC, TomRomeo commented
I finally came around to fix the logic and refactor the endpoints according to your comments. Could you take a look at this code again? @Julian702 @4KevR

2023-10-02 13:09 UTC, 4KevR requested changes
Looks good, see comments for minor improvements

2023-10-02 13:09 UTC, 4KevR commented on backend/services/frontend/handler/frontend.go
> +	}
```suggestion
	return c.SendStatus(200)
```

2023-10-02 13:09 UTC, 4KevR commented on backend/services/frontend/handler/frontend.go
> +		return helper.NewMicroNotSuccessfulResponseErr(helper.FrontendServiceID)
```suggestion
	if !rspDeleteUser.Success {
	      return helper.NewMicroNotSuccessfulResponseErr(helper.FrontendServiceID)
```

2023-10-02 13:09 UTC, 4KevR commented on backend/services/frontend/handler/frontend.go
> +	}
s.a.

2023-10-02 13:09 UTC, 4KevR commented on backend/services/user/handler/user.go
> +	usr, err := e.store.FindUserByEmail(req.UserEmail)
maybe `user`?

2023-10-02 13:15 UTC, darmiel requested changes

2023-10-02 13:15 UTC, darmiel commented on backend/services/collaboration/handler/collaboration.go
> +	}
```suggestion
	if len(remainingAdmins) == 1 && remainingAdmins[0].UserID == req.UserID {
		return helper.NewMicroCantLeaveAsLastAdminErr(helper.CollaborationServiceID)
	}
	return e.LeaveGroup(ctx, req, rsp)
```

2023-10-02 13:15 UTC, darmiel commented on backend/services/collaboration/handler/collaboration.go
> +	logger.Infof("User %s left group %s. ", req.UserID, req.GroupID)
```suggestion
	logger.Infof("User %s left group %s.", req.UserID, req.GroupID)
```

2023-10-02 13:15 UTC, darmiel commented on backend/services/frontend/handler/frontend.go
> +	}
```suggestion
	if err != nil {
		return err
	}
	if !rspDeleteUser.Success {
		return helper.NewMicroNotSuccessfulResponseErr(helper.FrontendServiceID)
	}
	return c.SendStatus(200)
```

2023-10-02 13:15 UTC, darmiel commented on backend/services/frontend/handler/frontend.go
> +	}
```suggestion
	if err != nil {
		return err
	}
	if !rspLeaveGroup.Success {
		return helper.NewMicroNotSuccessfulResponseErr(helper.FrontendServiceID)
	}
```

2023-10-02 13:15 UTC, darmiel commented on backend/store/store.go
> +	GetGroupAdmins(groupID string) ([]model.GroupUserRole, error)
```suggestion
	FindGroupMemberRoles(groupID string) ([]model.GroupUserRole, error)
	FindGroupAdmins(groupID string) ([]model.GroupUserRole, error)
```

2023-10-02 13:15 UTC, darmiel commented on backend/services/collaboration/handler/collaboration.go
> +		e.store.RemoveUserFromGroup(req.UserID, req.GroupID)
What about the error?

2023-10-02 13:15 UTC, darmiel commented on backend/services/collaboration/handler/collaboration.go
> +		e.store.DeleteGroup(group)
This error also waits to be handled :(

2023-10-02 13:15 UTC, darmiel commented on backend/services/collaboration/handler/collaboration.go
> +	logger.Infof("Received Collaboration.LeaveGroupSafe request: %v", req)
tip: use `%+v` instead of `%v` to display the keys in the struct

```go
{ Test 86 nil }
```
```go
{ Name:Test Age:86 Attributes:nil }
```

2023-10-02 13:32 UTC, TomRomeo commented on backend/store/store.go
> +	GetGroupAdmins(groupID string) ([]model.GroupUserRole, error)
As discussed with @Julian702 I will not change the naming here as it has been used before and is not completely written in one style. Furthermore, the functions are implemented at many points already.

2023-10-02 13:50 UTC, darmiel requested changes

2023-10-02 13:50 UTC, darmiel commented on backend/services/collaboration/handler/collaboration.go
> +	} else if group.GroupType == model.Public {
this code is never executed (`group.GroupType == model.Public` already covered this check above) - you probably just mixed up `||` and `&&`

2023-10-04 06:59 UTC, darmiel approved these changes

2023-10-04 07:21 UTC, Julian702 approved these changes
Looks good now, please just update the postman collection

2023-10-04 07:21 UTC, Julian702 commented on backend/kioku-api.postman_collection.json
> +					"raw": "127.0.0.1:3000/api/groups/:groupID/members/leave",
```suggestion
					"raw": "127.0.0.1:3000/api/groups/:groupID/members",
```

2023-10-04 08:08 UTC, 4KevR approved these changes

2023-10-04 09:04 UTC, merged