add: Notification for incoming invitations
kioku-project/kioku pull request #82
Opened 2023-09-07 14:11 UTC by Julian702

2023-09-07 14:54 UTC, darmiel requested changes

2023-09-07 14:54 UTC, darmiel commented on frontend/components/navigation/Tabs/TabHeader.tsx
> +	notification?: string;
this is rather the notification badge content, right?
I found it a bit confusing what you mean by that name. Maybe rename this to `notificationBadgeContent`

2023-09-07 14:54 UTC, darmiel commented on frontend/components/navigation/Tabs/TabHeader.tsx
> +				<div className="relative flex h-full text-sm text-kiokuDarkBlue">
`text-kiokuDarkBlue` is not as easily readable with a red background, as lighter colors, like white

2023-09-07 14:54 UTC, darmiel commented on frontend/pages/index.tsx
> +		groupInvitation: Pick<Group, "groupID" | "groupName">[];
maybe actually export this into it's own type. 
I've seen this now at least 4 times (`index.tsx`, `InvitationsTabs.tsx` (x2), `DeckOverview.tsx`)

2023-09-07 14:54 UTC, darmiel commented on frontend/pages/index.tsx
> +				notification={`${invitations?.groupInvitation?.length ?? ""}`}
Does it work so 0 notifications won't show up?
Just looking at this, \``0 ?? ""`\` => `"0"` and `!!"0"` => `true` which would be displayed as badge content:

```ts
{notification && (
{"0" && ( // <- here
```

```suggestion
				notification={`${invitations?.groupInvitation?.length || ""}`}
```

2023-09-07 19:00 UTC, Julian702 commented on frontend/pages/index.tsx
> +				notification={`${invitations?.groupInvitation?.length ?? ""}`}
Yeah, it's working fine, because there is no 0. If there is no invitation the statement on the left is evaluated to false since `invitations` is an empty dictionary and `groupInvitation` is therefore undefined. That's why an empty string is passed to the component and will not be rendered. However, your suggestion is the more robust solution and I will change that.

2023-09-08 07:26 UTC, Julian702 commented on frontend/pages/index.tsx
> +		groupInvitation: Pick<Group, "groupID" | "groupName">[];
It's used only twice (here in ìndex.tsx` and in the corresponding interface of `InvitationsTabs.tsx` ).

2023-09-08 12:14 UTC, Julian702 commented on frontend/pages/index.tsx
> +				notification={`${invitations?.groupInvitation?.length ?? ""}`}
fixed in 70fc959e6dc847955b455327040c2507f9ada2fe

2023-09-08 12:15 UTC, Julian702 commented on frontend/components/navigation/Tabs/TabHeader.tsx
> +	notification?: string;
changed in 70fc959e6dc847955b455327040c2507f9ada2fe

2023-09-08 12:16 UTC, darmiel commented on frontend/pages/index.tsx
> +				notification={`${invitations?.groupInvitation?.length ?? ""}`}
got it, thanks for clarifying.

2023-09-08 12:17 UTC, darmiel commented on frontend/pages/index.tsx
> +		groupInvitation: Pick<Group, "groupID" | "groupName">[];
I guess I've counted the type from changes which got overwritten by this PR.
Nevertheless, I think 3 times is enough for it to deserve it's own type.

2023-09-08 12:23 UTC, Julian702 commented on frontend/pages/index.tsx
> +		groupInvitation: Pick<Group, "groupID" | "groupName">[];
Well, then it's great that there are only two occurences ;)

2023-09-08 12:45 UTC, darmiel commented on frontend/pages/index.tsx
> +		groupInvitation: Pick<Group, "groupID" | "groupName">[];
:)

2023-09-08 13:52 UTC, darmiel approved these changes

2023-09-08 18:45 UTC, Julian702 commented on frontend/pages/index.tsx
> +		groupInvitation: Pick<Group, "groupID" | "groupName">[];
fixed in e1be87444b1908648153a6debe6c9e9ff5667af9

2023-09-09 04:47 UTC, 4KevR commented on frontend/components/navigation/Tabs/TabHeader.tsx
> +					<div className="absolute inline-flex h-full w-full animate-ping rounded-full bg-kiokuRed opacity-75"></div>
```suggestion
					<div className="absolute inline-flex h-full w-full animate-[ping_1s_ease-in-out_5] rounded-full bg-kiokuRed opacity-75"></div>
```
I don't know if I am a fan of the infinite ping of the badge. Maybe we can set a limit for it, the suggestion is just an idea.

2023-09-16 16:07 UTC, Julian702 commented on frontend/components/navigation/Tabs/TabHeader.tsx
> +					<div className="absolute inline-flex h-full w-full animate-ping rounded-full bg-kiokuRed opacity-75"></div>
fixed in 1163621cf64ae16eb60667af9a6c96e31a512f8d

2023-09-16 23:53 UTC, 4KevR approved these changes

2023-09-20 07:58 UTC, memeToasty approved these changes

2023-09-20 08:00 UTC, TomRomeo approved these changes

2023-09-21 10:09 UTC, merged