Adjust SettingsTabs according to group role
kioku-project/kioku pull request #84
Opened 2023-09-17 14:20 UTC by Julian702

This is how the GroupSettingsTab look like for a non-admin user.
![image](https://github.com/kioku-project/kioku/assets/66846059/a729c62a-8fd9-4c87-80c0-31f93c51cd42)

2023-09-20 07:58 UTC, memeToasty approved these changes

2023-09-20 09:04 UTC, darmiel requested changes
Just some smoll cosmetic things

2023-09-21 11:00 UTC, 4KevR approved these changes
I have nothing to add to the addressed points of @darmiel

2023-09-21 16:24 UTC, Julian702 commented on frontend/components/navigation/Tabs/DeckSettingsTab.tsx
> +
Needs an exclamation mark cause groupRole could be undefined.

2023-09-21 16:34 UTC, Julian702 commented on frontend/components/form/FormButton.tsx
> +		"bg-gray-500 border-gray-500 text-eggshell hover:cursor-not-allowed",
changed in ade302ef239c3f26966610301da7b48f1a48232d

2023-09-21 16:34 UTC, Julian702 commented on frontend/components/form/FormButton.tsx
> +			className={`flex justify-center rounded-md border-2 text-center font-semibold shadow-sm outline-none transition ${getStyle[style]} ${className} ${getSize[size]}`}
fixed in ade302ef239c3f26966610301da7b48f1a48232d

2023-09-21 16:34 UTC, Julian702 commented on frontend/components/form/FormButton.tsx
> +		"bg-gray-500 border-gray-500 text-eggshell hover:cursor-not-allowed",
fixed in ade302ef239c3f26966610301da7b48f1a48232d

2023-09-21 16:35 UTC, Julian702 commented on frontend/components/input/Button.tsx
> +		"bg-gray-500 border-gray-500 text-eggshell hover:cursor-not-allowed",
fixed in ade302ef239c3f26966610301da7b48f1a48232d

2023-09-21 16:35 UTC, Julian702 commented on frontend/components/input/Button.tsx
> +		"bg-transparent border-transparent text-kiokuDarkBlue hover:scale-105 hover:cursor-pointer",
added in ade302ef239c3f26966610301da7b48f1a48232d

2023-09-21 16:36 UTC, Julian702 commented on frontend/components/input/DangerAction.tsx
>  						onClick={onClick}
fixed in ade302ef239c3f26966610301da7b48f1a48232d

2023-09-21 16:38 UTC, Julian702 commented on frontend/components/navigation/Tabs/DeckSettingsTab.tsx
> +					description="Once you delete a deck, there is no going back. Please be certain."
paraphrased in ade302ef239c3f26966610301da7b48f1a48232d

2023-09-21 16:39 UTC, Julian702 commented on frontend/components/navigation/Tabs/GroupSettingsTab.tsx
> +					description="Once you delete a group, there is no going back. Please be certain."
paraphrased in ade302ef239c3f26966610301da7b48f1a48232d

2023-09-21 16:39 UTC, Julian702 commented on frontend/components/navigation/Tabs/GroupSettingsTab.tsx
> +						});
fixed in ade302ef239c3f26966610301da7b48f1a48232d

2023-09-22 12:15 UTC, darmiel approved these changes

2023-09-22 15:42 UTC, merged