Tracing
kioku-project/kioku pull request #92
Opened 2023-09-30 19:50 UTC by memeToasty

This PR adds tracing to our project.
With it we will be able to analyze resource usage and drill down on errors during runtime

2023-10-10 20:38 UTC, darmiel requested changes

2023-10-11 06:29 UTC, TomRomeo requested changes
Would be great if you could add documentation for this to the backend_development documentation. :)

2023-10-11 06:36 UTC, memeToasty commented
> Would be great if you could add documentation for this to the backend_development documentation. :)

Do you mean in the deployment documentation?

2023-10-11 06:38 UTC, Julian702 commented on backend/services/carddeck/main.go
> +	tp, _ := helper.SetupTracing(context.TODO(), service)
One error is waiting in the children's area to be picked up 🌞

2023-10-11 06:46 UTC, memeToasty commented on backend/services/collaboration/main.go
> +	tp, _ := helper.SetupTracing(context.TODO(), service)
fixed in [98f6174](https://github.com/kioku-project/kioku/pull/92/commits/98f61746a28b6ad6d7e033bd394f442318f2de08)

2023-10-11 06:46 UTC, memeToasty commented on backend/services/frontend/main.go
> +	tp, _ := helper.SetupTracing(context.TODO(), service)
fixed in [98f6174](https://github.com/kioku-project/kioku/pull/92/commits/98f61746a28b6ad6d7e033bd394f442318f2de08)

2023-10-11 06:46 UTC, memeToasty commented on backend/services/srs/main.go
> +	tp, _ := helper.SetupTracing(context.TODO(), service)
fixed in [98f6174](https://github.com/kioku-project/kioku/pull/92/commits/98f61746a28b6ad6d7e033bd394f442318f2de08)

2023-10-11 06:46 UTC, memeToasty commented on backend/services/user/main.go
> +	tp, _ := helper.SetupTracing(context.TODO(), service)
fixed in [98f6174](https://github.com/kioku-project/kioku/pull/92/commits/98f61746a28b6ad6d7e033bd394f442318f2de08)

2023-10-11 06:53 UTC, Julian702 approved these changes
Looks great, just make sure your squash commit doesn't look like your commit history ;)

2023-10-11 07:02 UTC, memeToasty commented
> Would be great if you could add documentation for this to the backend_development documentation. :)

added in [a996bf2](https://github.com/kioku-project/kioku/pull/92/commits/a996bf2dbd26396493748e97a34cca95fa108d16)

2023-10-11 07:13 UTC, TomRomeo requested changes

2023-10-11 07:13 UTC, TomRomeo commented on docs/backend_development.md
> +  - [Create a new service](#create-a-new-service)
This sadly happens automatically with Visual Studio Code 😭. Can you revert this?

2023-10-11 07:13 UTC, TomRomeo commented on docs/backend_development.md
> +    4. Instrument the service
reference that the following code is supposed to be added in `services/<name-of-new-service>/main.go`

2023-10-11 07:13 UTC, TomRomeo commented on docs/deployment.md
> +With the deployment, tracing capabilities will be deployed that can be accessed, when you forward the `ui` (`16686`) port of the `jaeger-service`.
The performance and metrics of the deployment such as dependencies between services can be viewed using `jaeger`. In order to access the jaeger frontend, you will have to expose the port `16686` of the `jaeger-service`

2023-10-11 07:14 UTC, 4KevR requested changes
Great work, I only have 2 points to address

2023-10-11 07:14 UTC, 4KevR commented on backend/pkg/helper/tracing.go
> +	}
Format is strange

2023-10-11 07:14 UTC, 4KevR commented on backend/services/carddeck/plugins.go
> +	_ "github.com/go-micro/plugins/v4/wrapper/trace/opentelemetry"
Is this import required, although you imported the module in the main.go of the service? (Not marking subsequent occurings)

2023-10-11 07:14 UTC, TomRomeo commented on backend/pkg/helper/tracing.go
> +	tracingUrl := os.Getenv("TRACING_COLLECTOR")
Please add additional environment variables to the .env.example file and document how to set them

2023-10-11 07:29 UTC, memeToasty commented on backend/services/carddeck/plugins.go
> +	_ "github.com/go-micro/plugins/v4/wrapper/trace/opentelemetry"
It says so in the documentation🤷‍♂️

2023-10-11 07:32 UTC, memeToasty commented on backend/pkg/helper/tracing.go
> +	tracingUrl := os.Getenv("TRACING_COLLECTOR")
The tracing architecture is not part of the local deployment, and I think we should not support it

2023-10-11 07:32 UTC, memeToasty commented on docs/backend_development.md
> +    4. Instrument the service
fixed in [7a7752a](https://github.com/kioku-project/kioku/pull/92/commits/7a7752a1f7dc510dad48c76cdefed3050c152514)

2023-10-11 07:37 UTC, memeToasty commented on docs/backend_development.md
> +  - [Create a new service](#create-a-new-service)
fixed in [7a7752a](https://github.com/kioku-project/kioku/pull/92/commits/7a7752a1f7dc510dad48c76cdefed3050c152514)

2023-10-11 07:38 UTC, memeToasty commented on backend/services/carddeck/main.go
> +	tp, _ := helper.SetupTracing(context.TODO(), service)
also fixed in [98f6174](https://github.com/kioku-project/kioku/pull/92/commits/98f61746a28b6ad6d7e033bd394f442318f2de08)😅

2023-10-11 07:39 UTC, memeToasty commented on backend/pkg/helper/tracing.go
> +	}
fixed in [09e9a19](https://github.com/kioku-project/kioku/pull/92/commits/09e9a198e6317fb68bd60a1e691ed069fb217b1a)

2023-10-11 07:40 UTC, memeToasty commented on docs/deployment.md
> +With the deployment, tracing capabilities will be deployed that can be accessed, when you forward the `ui` (`16686`) port of the `jaeger-service`.
fixed in [09e9a19](https://github.com/kioku-project/kioku/pull/92/commits/09e9a198e6317fb68bd60a1e691ed069fb217b1a)

2023-10-11 07:48 UTC, darmiel commented on backend/services/user/main.go
> +	tp, _ := helper.SetupTracing(context.TODO(), service)
Make it fatal

2023-10-11 07:48 UTC, darmiel commented on backend/services/srs/main.go
> +	tp, _ := helper.SetupTracing(context.TODO(), service)
sa

2023-10-11 07:48 UTC, darmiel commented on backend/services/frontend/main.go
> +	tp, _ := helper.SetupTracing(context.TODO(), service)
sasasa

2023-10-11 07:48 UTC, darmiel commented on backend/services/collaboration/main.go
> +	tp, _ := helper.SetupTracing(context.TODO(), service)
sasasasasa

2023-10-11 07:49 UTC, darmiel commented on backend/services/carddeck/main.go
> +	tp, _ := helper.SetupTracing(context.TODO(), service)
sasasasassasasasasasasasasasasasasasa

2023-10-11 08:47 UTC, darmiel requested changes

2023-10-11 08:47 UTC, darmiel commented on backend/pkg/helper/tracing.go
> +    } else {
don't `else` after `return`

2023-10-11 08:52 UTC, memeToasty commented on backend/pkg/helper/tracing.go
> +    } else {
fixed in [09e9a19](https://github.com/kioku-project/kioku/pull/92/commits/09e9a198e6317fb68bd60a1e691ed069fb217b1a)

2023-10-11 08:58 UTC, memeToasty commented on backend/pkg/helper/tracing.go
> +	tracingUrl := os.Getenv("TRACING_COLLECTOR")
Right now, in local deployment a STDOUT tracer will be used, but the output is disregarded, as it is just a spam of the logs. Effectively deactivating it. This can also be controlled by the `TRACING_ENABLED` environment variable now

2023-10-11 09:09 UTC, memeToasty commented on backend/services/srs/main.go
> +	tp, _ := helper.SetupTracing(context.TODO(), service)
fixed in [dde19ad](https://github.com/kioku-project/kioku/pull/92/commits/dde19ad8c1496dfd5368f0274b877480567f21fa)

2023-10-11 09:09 UTC, memeToasty commented on backend/services/frontend/main.go
> +	tp, _ := helper.SetupTracing(context.TODO(), service)
fixed in [dde19ad](https://github.com/kioku-project/kioku/pull/92/commits/dde19ad8c1496dfd5368f0274b877480567f21fa)

2023-10-11 09:09 UTC, memeToasty commented on backend/services/collaboration/main.go
> +	tp, _ := helper.SetupTracing(context.TODO(), service)
fixed in [dde19ad](https://github.com/kioku-project/kioku/pull/92/commits/dde19ad8c1496dfd5368f0274b877480567f21fa)

2023-10-11 09:09 UTC, memeToasty commented on backend/services/carddeck/main.go
> +	tp, _ := helper.SetupTracing(context.TODO(), service)
fixed in [dde19ad](https://github.com/kioku-project/kioku/pull/92/commits/dde19ad8c1496dfd5368f0274b877480567f21fa)

2023-10-11 10:36 UTC, 4KevR approved these changes

2023-10-11 11:05 UTC, darmiel commented on backend/pkg/helper/tracing.go
> +        return exporter, nil
```suggestion
        return tdouttrace.New(stdouttrace.WithWriter(io.Discard))
```

2023-10-11 11:05 UTC, darmiel commented on backend/pkg/helper/tracing.go
> +    return exporter, nil
```suggestion
    return otlptracehttp.New(
        ctx,
        otlptracehttp.WithEndpoint(tracingUrl),
        otlptracehttp.WithInsecure(),
    )
```

2023-10-11 11:52 UTC, memeToasty commented on backend/pkg/helper/tracing.go
> +    return exporter, nil
fixed in [a86b34b](https://github.com/kioku-project/kioku/pull/92/commits/a86b34bdb59b89e97f0cc190da9ebdec4b53b90d)

2023-10-11 11:52 UTC, memeToasty commented on backend/pkg/helper/tracing.go
> +        return exporter, nil
fixed in [a86b34b](https://github.com/kioku-project/kioku/pull/92/commits/a86b34bdb59b89e97f0cc190da9ebdec4b53b90d)

2023-10-11 12:11 UTC, TomRomeo approved these changes

2023-10-11 15:40 UTC, darmiel approved these changes

2023-10-11 16:55 UTC, merged